<?php

$files = array(
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/manifest.xml',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/template/tmpl/duplicate.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/items/tmpl/copy.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/types/view.raw.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/helpers/html/users.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/controllers/archive.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/models/base.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/models/archive.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/installation/install.mysql.nonutf8.sql',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/installation/uninstall.mysql.nonutf8.sql',
	JPATH_SITE . '/components/com_flexicontent/classes/flexicontent.acl.php',
	JPATH_SITE . '/components/com_flexicontent/classes/flexicontent.iptc.php',
	JPATH_SITE . '/plugins/flexicontent_fields/minigallery/css/minigallery.php',
	JPATH_SITE . '/plugins/flexicontent_fields/image/media/tmpl/default_fc.php',
	JPATH_SITE . '/components/com_flexicontent/librairies/fancybox/CHANGELOG.md',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/elements/qfcategory.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/models/qfcategoryelement.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/assets/js/copymove.js',
	JPATH_SITE . '/modules/mod_flexiadvsearch/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexicategories/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexicontent/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexifilter/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexigooglemap/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexitagcloud/elements/qfcategory.php',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-1.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-2.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-3.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-4.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-5.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-6.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/white.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/black.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/jush.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/js/jquery.opacityrollover.js',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/js/jush.js',
	JPATH_SITE . '/components/com_flexicontent/librairies/elastislide/css/style.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/elastislide/css/elastislide.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/elastislide/js/jquery.easing.1.3.js',
	JPATH_SITE . '/components/com_flexicontent/librairies/elastislide/js/gallery_tmpl.js',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/item/tmpl/tabs_main.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/item/tmpl/flat_main.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/item/tmpl/default_associations.php',
	JPATH_SITE . '/components/com_flexicontent/librairies/jquery/css/smoothness/jquery-ui-1.13.0.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/jquery/css/smoothness/jquery-ui-1.13.0.min.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/jquery/css/ui-lightness/jquery-ui-1.13.0.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/jquery/css/ui-lightness/jquery-ui-1.13.0.min.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/jquery/js/jquery-ui-1.13.1/package.json',
	//clean html5 file in common
	JPATH_SITE . '/components/com_flexicontent/tmpl_common/category_alpha_html5.php',
	JPATH_SITE . '/components/com_flexicontent/tmpl_common/category_category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/tmpl_common/category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/tmpl_common/category_peercategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/tmpl_common/category_subcategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/tmpl_common/listing_filter_form_body_html5.php',
	JPATH_SITE . '/components/com_flexicontent/tmpl_common/listing_filter_form_html5.php',
	JPATH_SITE . '/components/com_flexicontent/tmpl_common/item_layouts/modular_html5.php',
	//clean html5 file in grid
	JPATH_SITE . '/components/com_flexicontent/templates/grid/category_alpha_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/grid/category_category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/grid/category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/grid/category_peercategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/grid/category_subcategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/grid/item_html5.php',
	//clean html5 file in table
	JPATH_SITE . '/components/com_flexicontent/templates/table/category_alpha_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/table/category_category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/table/category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/table/category_peercategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/table/category_subcategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/table/item_html5.php',
	//clean html5 file in faq
	JPATH_SITE . '/components/com_flexicontent/templates/faq/category_alpha_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/faq/category_category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/faq/category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/faq/category_peercategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/faq/category_subcategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/faq/item_html5.php',
	//clean html5 file in item_tabbed
	JPATH_SITE . '/components/com_flexicontent/templates/item_tabbed/category_alpha_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/item_tabbed/category_category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/item_tabbed/category_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/item_tabbed/category_peercategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/item_tabbed/category_subcategories_html5.php',
	JPATH_SITE . '/components/com_flexicontent/templates/item_tabbed/item_html5.php',
);

$folders = array(
	JPATH_SITE . '/components/com_flexicontent/librairies/jquery/js/jquery-ui-1.13.0',
	JPATH_SITE . '/plugins/flexicontent_fields/image/media',
	JPATH_SITE . '/components/com_flexicontent/librairies/fancybox/source',
	JPATH_SITE . '/components/com_flexicontent/librairies/fancybox/lib',
	JPATH_SITE . '/components/com_flexicontent/librairies/echarts',
	JPATH_SITE . '/components/com_flexicontent/librairies/jquery/css/ui-smoothness',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/archive',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/qfcategoryelement',
);
