<?php

$files = array(
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/manifest.xml',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/items/tmpl/copy.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/types/view.raw.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/helpers/html/users.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/controllers/archive.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/models/base.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/models/archive.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/installation/install.mysql.nonutf8.sql',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/installation/uninstall.mysql.nonutf8.sql',
	JPATH_SITE . '/components/com_flexicontent/classes/flexicontent.acl.php',
	JPATH_SITE . '/components/com_flexicontent/classes/flexicontent.iptc.php',
	JPATH_SITE . '/plugins/flexicontent_fields/minigallery/css/minigallery.php',
	JPATH_SITE . '/plugins/flexicontent_fields/image/media/tmpl/default_fc.php',
	JPATH_SITE . '/components/com_flexicontent/librairies/fancybox/CHANGELOG.md',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/elements/qfcategory.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/models/qfcategoryelement.php',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/assets/js/copymove.js',
	JPATH_SITE . '/modules/mod_flexiadvsearch/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexicategories/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexicontent/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexifilter/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexigooglemap/elements/qfcategory.php',
	JPATH_SITE . '/modules/mod_flexitagcloud/elements/qfcategory.php',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-1.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-2.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-3.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-4.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-5.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/galleriffic-6.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/white.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/black.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/css/jush.css',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/js/jquery.opacityrollover.js',
	JPATH_SITE . '/components/com_flexicontent/librairies/galleriffic/js/jush.js',
);

$folders = array(
	JPATH_SITE . '/plugins/flexicontent_fields/image/media',
	JPATH_SITE . '/components/com_flexicontent/librairies/fancybox/source',
	JPATH_SITE . '/components/com_flexicontent/librairies/fancybox/lib',
	JPATH_SITE . '/components/com_flexicontent/librairies/echarts',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/archive',
	JPATH_ADMINISTRATOR . '/components/com_flexicontent/views/qfcategoryelement',
);
