files:
  - source: /**/en-GB/*.ini
    translation: /**/%locale%/%locale%.%file_name%.ini
    translation_replace:
      en-GB.: ""
  - source: /**/en-GB.*.ini
    translation: /**/%locale%.%file_name%.ini
    translation_replace:
      en-GB.: ""
