<?php
//No direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
// Some parameter shortcuts
$required = $field->parameters->get('required', 0);
$required = $required ? ' class="required"' : '';

$displayfieldaddr2 = $field->parameters->get('use-streetadress2', 0);
$displayfieldaddr2 = $displayfieldaddr2 ? '' : 'style="display:none"';

$displayfieldaddr3 = $field->parameters->get('use-streetadress3', 0);
$displayfieldaddr3 = $displayfieldaddr3 ? '' : 'style="display:none"';

$displayfieldusstate = $field->parameters->get('use-us-state', 0);;
$displayfieldusstate = $displayfieldusstate ? '' : 'style="display:none"';

$displayfieldprovince = $field->parameters->get('use-stateprovince', 0);
$displayfieldprovince = $displayfieldprovince ? '' : 'style="display:none"';

$displayfieldcountry = $field->parameters->get('use-unique-country', 0);
$displayfieldcountry = $displayfieldcountry ? 'style="display:none"' : '';



// States drop down list
$list_states = array(
	''=>JText::_('FLEXI_PLEASE_SELECT'),
	'AL'=>'Alabama',
	'AK'=>'Alaska',
	'AS'=>'American Samoa',
	'AZ'=>'Arizona',
	'AR'=>'Arkansas',
	'CA'=>'California',
	'CO'=>'Colorado',
	'CT'=>'Connecticut',
	'DE'=>'Delaware',
	'DC'=>'District of Columbia',
	'FL'=>'Florida',
	'GA'=>'Georgia',
	'GU'=>'Guam',
	'HI'=>'Hawaii',
	'ID'=>'Idaho',
	'IL'=>'Illinois',
	'IN'=>'Indiana',
	'IA'=>'Iowa',
	'KS'=>'Kansas',
	'KY'=>'Kentucky',
	'LA'=>'Louisiana',
	'ME'=>'Maine',
	'MH'=>'Marshall Islands',
	'MD'=>'Maryland',
	'MA'=>'Massachusetts',
	'MI'=>'Michigan',
	'MN'=>'Minnesota',
	'MS'=>'Mississippi',
	'MO'=>'Missouri',
	'MT'=>'Montana',
	'NE'=>'Nebraska',
	'NV'=>'Nevada',
	'NH'=>'New Hampshire',
	'NJ'=>'New Jersey',
	'NM'=>'New Mexico',
	'NY'=>'New York',
	'NC'=>'North Carolina',
	'ND'=>'North Dakota',
	'MP'=>'Northern Mariana Islands',
	'OH'=>'Ohio',
	'OK'=>'Oklahoma',
	'OR'=>'Oregon',
	'PW'=>'Palau',
	'PA'=>'Pennsylvania',
	'PR'=>'Puerto Rico',
	'RI'=>'Rhode Island',
	'SC'=>'South Carolina',
	'SD'=>'South Dakota',
	'TN'=>'Tennessee',
	'TX'=>'Texas',
	'UT'=>'Utah',
	'VT'=>'Vermont',
	'VI'=>'Virgin Islands',
	'VA'=>'Virginia',
	'WA'=>'Washington',
	'WV'=>'West Virginia',
	'WI'=>'Wisconsin',
	'WY'=>'Wyoming'
);

// Country drop down list
$list_countries = array(
	''=>JText::_('FLEXI_PLEASE_SELECT'),
	'AF'=>'Afghanistan',
	'AX'=>'&Aring;land Islands',
	'AL'=>'Albania',
	'DZ'=>'Algeria',
	'AS'=>'American Samoa',
	'AD'=>'Andorra',
	'AO'=>'Angola',
	'AI'=>'Anguilla',
	'AQ'=>'Antarctica',
	'AG'=>'Antigua and Barbuda',
	'AR'=>'Argentina',
	'AM'=>'Armenia',
	'AW'=>'Aruba',
	'AU'=>'Australia',
	'AT'=>'Austria',
	'AZ'=>'Azerbaijan',
	'BS'=>'Bahamas',
	'BH'=>'Bahrain',
	'BD'=>'Bangladesh',
	'BB'=>'Barbados',
	'BY'=>'Belarus',
	'BE'=>'Belgium',
	'BZ'=>'Belize',
	'BJ'=>'Benin',
	'BM'=>'Bermuda',
	'BT'=>'Bhutan',
	'BO'=>'Bolivia, Plurinational State of',
	'BQ'=>'Bonaire, Sint Eustatius and Saba',
	'BA'=>'Bosnia and Herzegovina',
	'BW'=>'Botswana',
	'BV'=>'Bouvet Island',
	'BR'=>'Brazil',
	'IO'=>'British Indian Ocean Territory',
	'BN'=>'Brunei Darussalam',
	'BG'=>'Bulgaria',
	'BF'=>'Burkina Faso',
	'BI'=>'Burundi',
	'KH'=>'Cambodia',
	'CM'=>'Cameroon',
	'CA'=>'Canada',
	'CV'=>'Cape Verde',
	'KY'=>'Cayman Islands',
	'CF'=>'Central African Republic',
	'TD'=>'Chad',
	'CL'=>'Chile',
	'CN'=>'China',
	'CX'=>'Christmas Island',
	'CC'=>'Cocos (Keeling) Islands',
	'CO'=>'Colombia',
	'KM'=>'Comoros',
	'CG'=>'Congo',
	'CD'=>'Congo, the Democratic Republic of the',
	'CK'=>'Cook Islands',
	'CR'=>'Costa Rica',
	'CI'=>'C&ocirc;te d\'Ivoire',
	'HR'=>'Croatia',
	'CU'=>'Cuba',
	'CW'=>'Cura&ccedil;ao',
	'CY'=>'Cyprus',
	'CZ'=>'Czech Republic',
	'DK'=>'Denmark',
	'DJ'=>'Djibouti',
	'DM'=>'Dominica',
	'DO'=>'Dominican Republic',
	'EC'=>'Ecuador',
	'EG'=>'Egypt',
	'SV'=>'El Salvador',
	'GQ'=>'Equatorial Guinea',
	'ER'=>'Eritrea',
	'EE'=>'Estonia',
	'ET'=>'Ethiopia',
	'FK'=>'Falkland Islands (Malvinas)',
	'FO'=>'Faroe Islands',
	'FJ'=>'Fiji',
	'FI'=>'Finland',
	'FR'=>'France',
	'GF'=>'French Guiana',
	'PF'=>'French Polynesia',
	'TF'=>'French Southern Territories',
	'GA'=>'Gabon',
	'GM'=>'Gambia',
	'GE'=>'Georgia',
	'DE'=>'Germany',
	'GH'=>'Ghana',
	'GI'=>'Gibraltar',
	'GR'=>'Greece',
	'GL'=>'Greenland',
	'GD'=>'Grenada',
	'GP'=>'Guadeloupe',
	'GU'=>'Guam',
	'GT'=>'Guatemala',
	'GG'=>'Guernsey',
	'GN'=>'Guinea',
	'GW'=>'Guinea-Bissau',
	'GY'=>'Guyana',
	'HT'=>'Haiti',
	'HM'=>'Heard Island and McDonald Islands',
	'VA'=>'Holy See (Vatican City State)',
	'HN'=>'Honduras',
	'HK'=>'Hong Kong',
	'HU'=>'Hungary',
	'IS'=>'Iceland',
	'IN'=>'India',
	'ID'=>'Indonesia',
	'IR'=>'Iran, Islamic Republic of',
	'IQ'=>'Iraq',
	'IE'=>'Ireland',
	'IM'=>'Isle of Man',
	'IL'=>'Israel',
	'IT'=>'Italy',
	'JM'=>'Jamaica',
	'JP'=>'Japan',
	'JE'=>'Jersey',
	'JO'=>'Jordan',
	'KZ'=>'Kazakhstan',
	'KE'=>'Kenya',
	'KI'=>'Kiribati',
	'KP'=>'Korea, Democratic People\'s Republic of',
	'KR'=>'Korea, Republic of',
	'KW'=>'Kuwait',
	'KG'=>'Kyrgyzstan',
	'LA'=>'Lao People\'s Democratic Republic',
	'LV'=>'Latvia',
	'LB'=>'Lebanon',
	'LS'=>'Lesotho',
	'LR'=>'Liberia',
	'LY'=>'Libya',
	'LI'=>'Liechtenstein',
	'LT'=>'Lithuania',
	'LU'=>'Luxembourg',
	'MO'=>'Macao',
	'MK'=>'Macedonia, the former Yugoslav Republic of',
	'MG'=>'Madagascar',
	'MW'=>'Malawi',
	'MY'=>'Malaysia',
	'MV'=>'Maldives',
	'ML'=>'Mali',
	'MT'=>'Malta',
	'MH'=>'Marshall Islands',
	'MQ'=>'Martinique',
	'MR'=>'Mauritania',
	'MU'=>'Mauritius',
	'YT'=>'Mayotte',
	'MX'=>'Mexico',
	'FM'=>'Micronesia, Federated States of',
	'MD'=>'Moldova, Republic of',
	'MC'=>'Monaco',
	'MN'=>'Mongolia',
	'ME'=>'Montenegro',
	'MS'=>'Montserrat',
	'MA'=>'Morocco',
	'MZ'=>'Mozambique',
	'MM'=>'Myanmar',
	'NA'=>'Namibia',
	'NR'=>'Nauru',
	'NP'=>'Nepal',
	'NL'=>'Netherlands',
	'NC'=>'New Caledonia',
	'NZ'=>'New Zealand',
	'NI'=>'Nicaragua',
	'NE'=>'Niger',
	'NG'=>'Nigeria',
	'NU'=>'Niue',
	'NF'=>'Norfolk Island',
	'MP'=>'Northern Mariana Islands',
	'NO'=>'Norway',
	'OM'=>'Oman',
	'PK'=>'Pakistan',
	'PW'=>'Palau',
	'PS'=>'Palestinian Territory, Occupied',
	'PA'=>'Panama',
	'PG'=>'Papua New Guinea',
	'PY'=>'Paraguay',
	'PE'=>'Peru',
	'PH'=>'Philippines',
	'PN'=>'Pitcairn',
	'PL'=>'Poland',
	'PT'=>'Portugal',
	'PR'=>'Puerto Rico',
	'QA'=>'Qatar',
	'RE'=>'R&eacute;union',
	'RO'=>'Romania',
	'RU'=>'Russian Federation',
	'RW'=>'Rwanda',
	'BL'=>'Saint Barth&eacute;lemy',
	'SH'=>'Saint Helena, Ascension and Tristan da Cunha',
	'KN'=>'Saint Kitts and Nevis',
	'LC'=>'Saint Lucia',
	'MF'=>'Saint Martin (French part)',
	'PM'=>'Saint Pierre and Miquelon',
	'VC'=>'Saint Vincent and the Grenadines',
	'WS'=>'Samoa',
	'SM'=>'San Marino',
	'ST'=>'Sao Tome and Principe',
	'SA'=>'Saudi Arabia',
	'SN'=>'Senegal',
	'RS'=>'Serbia',
	'SC'=>'Seychelles',
	'SL'=>'Sierra Leone',
	'SG'=>'Singapore',
	'SX'=>'Sint Maarten (Dutch part)',
	'SK'=>'Slovakia',
	'SI'=>'Slovenia',
	'SB'=>'Solomon Islands',
	'SO'=>'Somalia',
	'ZA'=>'South Africa',
	'GS'=>'South Georgia and the South Sandwich Islands',
	'SS'=>'South Sudan',
	'ES'=>'Spain',
	'LK'=>'Sri Lanka',
	'SD'=>'Sudan',
	'SR'=>'Suriname',
	'SJ'=>'Svalbard and Jan Mayen',
	'SZ'=>'Swaziland',
	'SE'=>'Sweden',
	'CH'=>'Switzerland',
	'SY'=>'Syrian Arab Republic',
	'TW'=>'Taiwan, Province of China',
	'TJ'=>'Tajikistan',
	'TZ'=>'Tanzania, United Republic of',
	'TH'=>'Thailand',
	'TL'=>'Timor-Leste',
	'TG'=>'Togo',
	'TK'=>'Tokelau',
	'TO'=>'Tonga',
	'TT'=>'Trinidad and Tobago',
	'TN'=>'Tunisia',
	'TR'=>'Turkey',
	'TM'=>'Turkmenistan',
	'TC'=>'Turks and Caicos Islands',
	'TV'=>'Tuvalu',
	'UG'=>'Uganda',
	'UA'=>'Ukraine',
	'AE'=>'United Arab Emirates',
	'GB'=>'United Kingdom',
	'US'=>'United States',
	'UM'=>'United States Minor Outlying Islands',
	'UY'=>'Uruguay',
	'UZ'=>'Uzbekistan',
	'VU'=>'Vanuatu',
	'VE'=>'Venezuela, Bolivarian Republic of',
	'VN'=>'Viet Nam',
	'VG'=>'Virgin Islands, British',
	'VI'=>'Virgin Islands, U.S.',
	'WF'=>'Wallis and Futuna',
	'EH'=>'Western Sahara',
	'YE'=>'Yemen',
	'ZM'=>'Zambia',
	'ZW'=>'Zimbabwe'
);

$n = 0;
foreach ($values as $value)
{
	$field->html[$n] = '
	<table class="admintable"><tbody>
		<tr>
			<td class="label label-info">'.JText::_('PLG_FLEXICONTENT_FIELDS_ADDRESSINT_STREET_ADDRESS').':</td>
			<td><input type="text" class="fcfield_textval" name="custom['.$field->name.'][addr1]" value="'.$value['addr1'].'" size="50" maxlength="100"'.$required.' /></td>
		</tr><tr '.$displayfieldaddr2.'>
			<td class="label label-info">&nbsp;</td>
			<td><input type="text" class="fcfield_textval"  name="custom['.$field->name.'][addr2]" value="'.$value['addr2'].'" size="50" maxlength="100" /></td>
		</tr><tr '.$displayfieldaddr3.'>
			<td class="label label-info">&nbsp;</td>
			<td><input type="text" class="fcfield_textval"  name="custom['.$field->name.'][addr3]" value="'.$value['addr3'].'" size="50" maxlength="100" /></td>
		</tr><tr>
			<td class="label label-info">'.JText::_('PLG_FLEXICONTENT_FIELDS_ADDRESSINT_CITY').':</td>
			<td><input type="text" class="fcfield_textval" name="custom['.$field->name.'][city]" id="city" value="'.$value['city'].'" size="50" maxlength="100" /></td>
		</tr><tr '.$displayfieldusstate.'>
			<td class="label label-info">'.JText::_('PLG_FLEXICONTENT_FIELDS_ADDRESSINT_US_STATE').':</td>
			<td>'.JHTML::_('select.genericlist', $list_states, 'custom['.$field->name.'][state]', $required, 'value', 'text', $value['state']).'</td>
		</tr><tr '.$displayfieldprovince.'>
			<td class="label label-info">'.JText::_('PLG_FLEXICONTENT_FIELDS_ADDRESSINT_NON_US_STATE_PROVINCE').':</td>
			<td><input type="text" class="fcfield_textval" name="custom['.$field->name.'][province]" value="'.$value['province'].'" size="50" maxlength="100" /></td>
		</tr><tr>
			<td class="label label-info">'.JText::_('PLG_FLEXICONTENT_FIELDS_ADDRESSINT_ZIP_POSTAL_CODE').':</td>
			<td><input type="text" class="fcfield_textval" name="custom['.$field->name.'][zip]" value="'.$value['zip'].'" size="10" maxlength="10"'.$required.' /></td>
		</tr><tr '.$displayfieldcountry.'>
			<td class="label label-info">'.JText::_('PLG_FLEXICONTENT_FIELDS_ADDRESSINT_COUNTRY').':</td>
			<td>'.JHTML::_('select.genericlist', $list_countries, 'custom['.$field->name.'][country]', $required, 'value', 'text', $value['country']).'</td>
		</tr><tr>
			<td></td><td><input class="fcfield-button" type="button" value="'.JText::_('PLG_FLEXICONTENT_FIELDS_ADDRESSINT_GEOLOCATE').'" onclick="geolocateAddr(\'custom['.$field->name.']\', \''.$field->name.'\');" /> <input type="text" class="fcfield_textval" name="custom['.$field->name.'][lat]" value="'.$value['lat'].'" size="5" maxlength="10"'.$required.' readonly="readonly" style="width: 50px !important;
    min-width: 70px !important;" /> <input type="text" class="fcfield_textval" name="custom['.$field->name.'][lon]" value="'.$value['lon'].'" size="5" maxlength="10"'.$required.' readonly="readonly" style="width: 50px !important;
    min-width: 70px !important;margin-bottom: 7px;"/> <div id="'.$field->name.'_map"><img src="http://maps.google.com/maps/api/staticmap?center='.$value['lat'].','.$value['lon'].'&amp;zoom=12&amp;size=320x240&amp;maptype=roadmap&amp;markers=size:mid%7Ccolor:red%7C|'.$value['lat'].','.$value['lon'].'&amp;sensor=false" alt="" /></div></td>
		</tr>
	</tbody></table>
	';
	
	$n++;
	break; // Only 1 value currently allowed
}