<?php
defined( '_JEXEC' ) or die( 'Restricted access' );

use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Uri\Uri;

class flexicontent_images
{
	/**
	 * phpThumb library folder, relative to the site root
	 */
	const PHPTHUMB_REL_DIR = 'components/com_flexicontent/librairies/phpthumb';

	/**
	 * Configuration file generated by FLEXIcontent (high security flag and signing key).
	 * It is loaded by phpThumb.config.php after the shipped defaults and before phpThumb.config_OVERRIDE.php
	 */
	const PHPTHUMB_MANAGED_FILE = 'phpThumb.config_FLEXI.php';

	/**
	 * Output formats that phpThumb can be asked for via the 'f' parameter
	 */
	const PHPTHUMB_FORMATS = array('png', 'gif', 'jpeg', 'jpg', 'webp', 'wbmp', 'bmp', 'ico');

	/**
	 * Minimum key strength accepted by phpThumb (see phpthumb_functions::PasswordStrength())
	 */
	const PHPTHUMB_MIN_KEY_STRENGTH = 20;

	/**
	 * Snapshot of the effective phpThumb configuration ($PHPTHUMB_CONFIG after the managed and override files)
	 */
	private static $phpthumb_config = null;


	/**
	 * Absolute path of the phpThumb library folder
	 *
	 * @return  string
	 */
	static function phpThumbDir()
	{
		return JPATH_SITE . '/' . self::PHPTHUMB_REL_DIR;
	}


	/**
	 * URL of the phpThumb script
	 *
	 * @param   bool  $absolute  Return an absolute URL (scheme and host) instead of a root-relative one
	 *
	 * @return  string
	 */
	static function phpThumbEndpoint($absolute = false)
	{
		return ($absolute ? Uri::root() : Uri::root(true) . '/') . self::PHPTHUMB_REL_DIR . '/phpThumb.php';
	}


	/**
	 * Load the effective phpThumb configuration once, exactly as phpThumb.php loads it
	 * (shipped defaults, then phpThumb.config_FLEXI.php, then phpThumb.config_OVERRIDE.php),
	 * so that URLs are signed with the key and settings the script will verify them with.
	 *
	 * @param   bool  $reload  Discard the cached snapshot
	 *
	 * @return  array  The $PHPTHUMB_CONFIG array, empty if the library is missing
	 */
	static function phpThumbConfig($reload = false)
	{
		if (self::$phpthumb_config !== null && !$reload)
		{
			return self::$phpthumb_config;
		}

		$config_file = self::phpThumbDir() . '/phpThumb.config.php';
		self::$phpthumb_config = array();

		if (!is_file($config_file))
		{
			return self::$phpthumb_config;
		}

		/**
		 * The configuration file declares $PHPTHUMB_CONFIG as global and also copies it to $GLOBALS.
		 * Include it only once: a second include would reset the array to the shipped defaults
		 * without re-applying the managed and override files (they are loaded with include_once).
		 */
		include_once $config_file;

		if (!empty($GLOBALS['PHPTHUMB_CONFIG']) && is_array($GLOBALS['PHPTHUMB_CONFIG']))
		{
			self::$phpthumb_config = $GLOBALS['PHPTHUMB_CONFIG'];
		}

		return self::$phpthumb_config;
	}


	/**
	 * Key used to sign phpThumb URLs, empty when there is no usable key
	 *
	 * @return  string
	 */
	static function phpThumbKey()
	{
		$config = self::phpThumbConfig();
		$key    = isset($config['high_security_password']) ? (string) $config['high_security_password'] : '';

		// phpThumb refuses weak keys when it enforces signatures, do not sign with them either
		return self::phpThumbKeyStrength($key) >= self::PHPTHUMB_MIN_KEY_STRENGTH ? $key : '';
	}


	/**
	 * Whether phpThumb.php currently refuses unsigned URLs (effective value, after the override file)
	 *
	 * @return  bool
	 */
	static function phpThumbEnforced()
	{
		$config = self::phpThumbConfig();

		return !empty($config['high_security_enabled']);
	}


	/**
	 * Key strength as computed by phpthumb_functions::PasswordStrength(), duplicated here so that the
	 * managed file can be checked without loading the whole library
	 *
	 * @param   string  $key
	 *
	 * @return  float
	 */
	static function phpThumbKeyStrength($key)
	{
		$key = (string) $key;

		return
			strlen(preg_replace('#[^a-z]#', '', $key)) * 0.5 +
			strlen(preg_replace('#[^A-Z]#', '', $key)) * 0.8 +
			strlen(preg_replace('#[^0-9]#', '', $key)) * 1.0 +
			strlen(preg_replace('#[a-zA-Z0-9]#', '', $key)) * 2.0;
	}


	/**
	 * Convert an image path as used by FLEXIcontent (relative to the site root, root-relative, or an absolute URL)
	 * to the 'src' parameter expected by phpThumb.php
	 *
	 * @param   string  $src
	 *
	 * @return  string
	 */
	static function phpThumbSrc($src)
	{
		$src = str_replace('\\', '/', trim((string) $src));

		if ($src === '' || preg_match('#^(https?:|ftp:)?//#i', $src) || $src[0] === '/')
		{
			return $src;
		}

		return Uri::root(true) . '/' . $src;
	}


	/**
	 * Output format ('f' parameter) that keeps the format of the given image, empty when phpThumb should decide
	 *
	 * @param   string  $src  Image path or URL
	 *
	 * @return  string
	 */
	static function phpThumbFormat($src)
	{
		$ext = strtolower(pathinfo(parse_url((string) $src, PHP_URL_PATH) ?: (string) $src, PATHINFO_EXTENSION));

		return in_array($ext, self::PHPTHUMB_FORMATS, true) ? $ext : '';
	}


	/**
	 * Build a phpThumb URL, signed when a key is available
	 *
	 * Example:
	 *   flexicontent_images::phpThumbURL(array('src' => 'images/pic.jpg', 'w' => 100, 'h' => 100, 'zc' => 1, 'q' => 95, 'ar' => 'x'))
	 *
	 * Parameters with an empty value (null, false or '') are skipped, an array value is passed as name[]=...
	 * (e.g. 'fltr' => array('blur|2')). 'src' is passed through phpThumbSrc() unless $raw_src is true.
	 *
	 * @param   array|string  $params    phpThumb parameters (array, or a query string like 'src=/images/pic.jpg&w=100')
	 * @param   bool          $html      Escape the URL for use inside an HTML attribute
	 * @param   bool          $absolute  Use an absolute URL for the phpThumb script (feeds, emails)
	 * @param   bool          $raw_src   Pass 'src' as given, without resolving it relative to the site root
	 *
	 * @return  string
	 */
	static function phpThumbURL($params, $html = true, $absolute = false, $raw_src = false)
	{
		if (!is_array($params))
		{
			parse_str(str_replace('&amp;', '&', (string) $params), $params);
		}

		if (isset($params['src']) && !$raw_src)
		{
			$params['src'] = self::phpThumbSrc($params['src']);
		}

		$query = self::phpThumbQuery($params);
		$url   = self::phpThumbEndpoint($absolute) . '?' . $query;

		return $html ? htmlspecialchars($url, ENT_QUOTES, 'UTF-8') : $url;
	}


	/**
	 * Build the query string of a phpThumb URL and append the signature, using the same encoding
	 * as phpThumbURL() of phpThumb.config.php, so that phpThumb.php accepts it when high security is on
	 *
	 * @param   array  $params
	 *
	 * @return  string
	 */
	static function phpThumbQuery(array $params)
	{
		$config    = self::phpThumbConfig();
		$separator = !empty($config['high_security_url_separator']) ? $config['high_security_url_separator'] : '&';
		$parts     = array();

		unset($params['hash']);

		foreach ($params as $name => $value)
		{
			if (is_array($value))
			{
				foreach ($value as $sub_value)
				{
					if ($sub_value === null || $sub_value === false || $sub_value === '')
					{
						continue;
					}

					$parts[] = $name . '[]=' . rawurlencode((string) $sub_value);
				}
			}
			elseif ($value !== null && $value !== false && $value !== '')
			{
				$parts[] = $name . '=' . rawurlencode((string) $value);
			}
		}

		$query = implode($separator, $parts);
		$key   = self::phpThumbKey();

		return $key === ''
			? $query
			: $query . $separator . 'hash=' . hash_hmac('sha256', $query, $key);
	}


	/**
	 * Sign the phpThumb URLs of rendered HTML that were not created via phpThumbURL()
	 * (custom templates, module layouts, content), so that they keep working when signatures are enforced.
	 *
	 * Only image and style contexts are signed: src, srcset, data-src, data-srcset, data-lazy-src, poster
	 * and href attributes, style attributes and <style> blocks. Text nodes, form fields, scripts and every
	 * other attribute are left alone, so a URL reflected from user input (search terms, comments, form
	 * values) can never be used to obtain a signature. Textarea contents (edit forms) are never modified.
	 * URLs that already carry a valid signature are left untouched, URLs with a stale signature (key
	 * regenerated) are re-signed.
	 *
	 * @param   string  $html
	 *
	 * @return  string
	 */
	static function phpThumbSignHtml($html)
	{
		if (!is_string($html) || strpos($html, 'phpThumb.php?') === false)
		{
			return $html;
		}

		$key = self::phpThumbKey();

		if ($key === '')
		{
			return $html;
		}

		$config    = self::phpThumbConfig();
		$separator = !empty($config['high_security_url_separator']) ? $config['high_security_url_separator'] : '&';

		/**
		 * Sign one query string (the part after 'phpThumb.php?'), given as it appears in the HTML
		 */
		$sign_query = function ($query) use ($key, $separator)
		{
			$encoded = strpos($query, '&amp;') !== false;
			$raw     = $encoded ? str_replace('&amp;', '&', $query) : $query;

			// Already signed with the current key
			if (preg_match('#(?:^|&)hash=([0-9a-f]{64})#', $raw, $hash_match))
			{
				$unsigned = str_replace($separator . 'hash=' . $hash_match[1], '', $raw);

				if (hash_equals(hash_hmac('sha256', $unsigned, $key), $hash_match[1]))
				{
					return $query;
				}
			}

			parse_str($raw, $params);

			if (empty($params['src']) || !is_string($params['src']))
			{
				return $query;
			}

			$signed = self::phpThumbQuery($params);

			return $encoded ? str_replace('&', '&amp;', $signed) : $signed;
		};

		$marker = 'phpThumb.php?';

		/**
		 * Sign a single URL that may contain unencoded spaces (everything after the marker is the query)
		 */
		$sign_url = function ($url) use ($sign_query, $marker)
		{
			$pos = strpos($url, $marker);

			if ($pos === false)
			{
				return $url;
			}

			$pos += strlen($marker);

			return substr($url, 0, $pos) . $sign_query(trim(substr($url, $pos)));
		};

		/**
		 * Sign every url(...) of a CSS text (style attribute or <style> block)
		 */
		$sign_css = function ($css) use ($sign_url, $marker)
		{
			if (strpos($css, $marker) === false)
			{
				return $css;
			}

			return preg_replace_callback('#(url\(\s*)(["\']?)([^"\')]*' . preg_quote($marker, '#') . '[^"\')]*)\2(\s*\))#i', function ($m) use ($sign_url)
			{
				return $m[1] . $m[2] . $sign_url($m[3]) . $m[2] . $m[4];
			}, $css);
		};

		/**
		 * Sign the value of an image attribute: a single URL, or a srcset list of "url descriptor" candidates
		 */
		$sign_value = function ($value) use ($sign_url, $marker)
		{
			if (strpos($value, $marker) === false)
			{
				return $value;
			}

			if (preg_match('#\s\d+(?:\.\d+)?[wx]\s*(?:,|$)#', $value))
			{
				$candidates = preg_split('#\s*,\s*(?=\S)#', $value);

				foreach ($candidates as $c => $candidate)
				{
					if (preg_match('#^(.*?)(\s+\d+(?:\.\d+)?[wx])?$#s', $candidate, $parts))
					{
						$candidates[$c] = $sign_url($parts[1]) . ($parts[2] ?? '');
					}
				}

				return implode(', ', $candidates);
			}

			return $sign_url($value);
		};

		$sign_attributes = function ($chunk) use ($sign_value, $sign_css, $marker)
		{
			// Attributes that carry image URLs (single URL or srcset list), quoted values only
			$chunk = preg_replace_callback(
				'#(\s(?:src|srcset|data-src|data-srcset|data-lazy-src|data-lazy-srcset|data-original|poster|href)\s*=\s*)(["\'])((?:(?!\2)[^<>])*' . preg_quote($marker, '#') . '(?:(?!\2)[^<>])*)\2#i',
				function ($m) use ($sign_value)
				{
					return $m[1] . $m[2] . $sign_value($m[3]) . $m[2];
				},
				$chunk
			);

			// Inline styles
			$chunk = preg_replace_callback(
				'#(\sstyle\s*=\s*)(["\'])((?:(?!\2)[^<>])*' . preg_quote($marker, '#') . '(?:(?!\2)[^<>])*)\2#i',
				function ($m) use ($sign_css)
				{
					return $m[1] . $m[2] . $sign_css($m[3]) . $m[2];
				},
				$chunk
			);

			// Style blocks
			return preg_replace_callback('#(<style\b[^>]*>)(.*?)(</style>)#is', function ($m) use ($sign_css)
			{
				return $m[1] . $sign_css($m[2]) . $m[3];
			}, $chunk);
		};

		// Leave form contents alone (e.g. an article being edited in the frontend)
		$chunks = preg_split('#(<textarea\b[^>]*>.*?</textarea>)#is', $html, -1, PREG_SPLIT_DELIM_CAPTURE);

		foreach ($chunks as $i => $chunk)
		{
			if ($i % 2 === 0 && strpos($chunk, $marker) !== false)
			{
				$chunks[$i] = $sign_attributes($chunk);
			}
		}

		return implode('', $chunks);
	}


	/**
	 * Absolute path of the configuration file generated by FLEXIcontent
	 *
	 * @return  string
	 */
	static function phpThumbManagedFile()
	{
		return self::phpThumbDir() . '/' . self::PHPTHUMB_MANAGED_FILE;
	}


	/**
	 * Read the configuration file generated by FLEXIcontent, without loading the phpThumb configuration
	 *
	 * @return  array  exists, writable, enabled (null when the file does not exist), key
	 */
	static function phpThumbManagedState()
	{
		$file  = self::phpThumbManagedFile();
		$state = array(
			'file'     => $file,
			'exists'   => is_file($file),
			'writable' => is_file($file) ? is_writable($file) : is_writable(dirname($file)),
			'enabled'  => null,
			'key'      => '',
		);

		// Parse instead of include: including it here would satisfy the include_once() of phpThumb.config.php,
		// which would then skip it and lose the key. The file is generated by phpThumbSyncConfig() below.
		if ($state['exists'])
		{
			$content = (string) file_get_contents($file);

			$state['enabled'] = preg_match("/\\\$PHPTHUMB_CONFIG\\['high_security_enabled'\\]\\s*=\\s*true\\s*;/", $content) === 1;
			$state['key']     = preg_match("/\\\$PHPTHUMB_CONFIG\\['high_security_password'\\]\\s*=\\s*'([^']*)'\\s*;/", $content, $m) ? $m[1] : '';
		}

		return $state;
	}


	/**
	 * Create a new random signing key
	 *
	 * @return  string
	 */
	static function phpThumbGenerateKey()
	{
		return bin2hex(random_bytes(32));
	}


	/**
	 * (Re)write the configuration file generated by FLEXIcontent so that it matches the component configuration.
	 * The signing key is kept unless it is missing, too weak, or a new one is requested.
	 *
	 * @param   bool       $regenerate_key  Create a new key even if a usable one exists
	 * @param   bool|null  $enabled         Enforce signatures (null: use the component configuration)
	 *
	 * @return  bool|null  true when the file was written, null when it was already up to date, false on failure
	 */
	static function phpThumbSyncConfig($regenerate_key = false, $enabled = null)
	{
		if ($enabled === null)
		{
			$enabled = (bool) ComponentHelper::getParams('com_flexicontent')->get('phpthumb_high_security', 0);
		}

		$enabled = (bool) $enabled;
		$state   = self::phpThumbManagedState();
		$key     = $state['key'];

		if ($regenerate_key || self::phpThumbKeyStrength($key) < self::PHPTHUMB_MIN_KEY_STRENGTH)
		{
			$key = self::phpThumbGenerateKey();
		}

		if ($state['exists'] && $state['enabled'] === $enabled && $state['key'] === $key)
		{
			return null;
		}

		$content =
			'<?php' . "\n" .
			'/**' . "\n" .
			' * phpThumb configuration managed by FLEXIcontent. DO NOT EDIT THIS FILE:' . "\n" .
			' * it is rewritten whenever the FLEXIcontent configuration is saved.' . "\n" .
			' * Put manual overrides in phpThumb.config_OVERRIDE.php, which is loaded after this file.' . "\n" .
			' *' . "\n" .
			' * high_security_enabled : when true phpThumb.php only serves URLs signed with the key below,' . "\n" .
			' *                         FLEXIcontent signs the URLs it generates via flexicontent_images::phpThumbURL()' . "\n" .
			' * high_security_password: secret signing key, keep it private (regenerate it from the FLEXIcontent configuration)' . "\n" .
			' *' . "\n" .
			' * Generated: ' . gmdate('Y-m-d H:i:s') . ' UTC' . "\n" .
			' */' . "\n" .
			"\n" .
			'$PHPTHUMB_CONFIG[\'high_security_enabled\']  = ' . ($enabled ? 'true' : 'false') . ';' . "\n" .
			'$PHPTHUMB_CONFIG[\'high_security_password\'] = \'' . $key . '\';' . "\n";

		$file = $state['file'];
		$tmp  = $file . '.' . uniqid('', true) . '.tmp';

		$written = @file_put_contents($tmp, $content) !== false && (@rename($tmp, $file) || @copy($tmp, $file));
		@unlink($tmp);

		if (!$written)
		{
			return false;
		}

		@chmod($file, 0644);

		if (function_exists('opcache_invalidate'))
		{
			@opcache_invalidate($file, true);
		}

		// The configuration snapshot (if any) is now stale
		self::$phpthumb_config = null;

		if (isset($GLOBALS['PHPTHUMB_CONFIG']) && is_array($GLOBALS['PHPTHUMB_CONFIG']))
		{
			$GLOBALS['PHPTHUMB_CONFIG']['high_security_enabled']  = $enabled;
			$GLOBALS['PHPTHUMB_CONFIG']['high_security_password'] = $key;
			self::$phpthumb_config = $GLOBALS['PHPTHUMB_CONFIG'];
		}

		return true;
	}


	/**
	 * Get file size and icons
	 *
	 * @since 1.5
	 */
	static function BuildIcons($rows, $default_text = null)
	{
		jimport('joomla.filesystem.path' );
		jimport('joomla.filesystem.file');
		$NA = '-';

		for ($i=0, $n=count($rows); $i < $n; $i++)
		{
			$basePath = $rows[$i]->secure ? COM_FLEXICONTENT_FILEPATH : COM_FLEXICONTENT_MEDIAPATH;

			if ($rows[$i]->url)
			{
				$size = (int)$rows[$i]->size ? (int)$rows[$i]->size : $NA;
			}
			else if (is_file($basePath.DS.$rows[$i]->filename))
			{
				if (empty($rows[$i]->size))
				{
					$size = $default_text ?: filesize(str_replace(DS, '/', \Joomla\Filesystem\Path::clean($basePath.DS.$rows[$i]->filename)));
				}
				else
				{
					$size = $rows[$i]->size;
				}
			}
			else
			{
				$size = $NA;
			}

			if (is_numeric($size))
			{
				if ($size < 1024)
				{
					$rows[$i]->size = $size . ' bytes';
				}
				else
				{
					$rows[$i]->size = $size < 1024 * 1024
						? sprintf('%01.2f', $size / 1024.0) . ' KBs'
						: sprintf('%01.2f', $size / (1024.0 * 1024)) . ' MBs';
				}
			}
			else
			{
				$rows[$i]->size = $size;
			}

			if ($rows[$i]->url == 1)
			{
				$ext = $rows[$i]->ext;
			} else {
				$ext = strtolower(flexicontent_upload::getExt($rows[$i]->filename));
			}
			switch ($ext)
			{
				// Image
				case 'jpg':
				case 'png':
				case 'gif':
				case 'xcf':
				case 'odg':
				case 'wbmp':
				case 'bmp':
				case 'ico':
				case 'jpeg':
				case 'webp':
					$rows[$i]->icon = 'components/com_flexicontent/assets/images/mime-icon-16/image.png';
					break;

				// Non-image document
				default:
					$icon = JPATH_SITE.DS.'components'.DS.'com_flexicontent'.DS.'assets'.DS.'images'.DS.'mime-icon-16'.DS.$ext.'.png';
					$rows[$i]->icon = file_exists($icon)
						? 'components/com_flexicontent/assets/images/mime-icon-16/'.$ext.'.png'
						: 'components/com_flexicontent/assets/images/mime-icon-16/unknown.png';
					break;
			}
		}

		return $rows;
	}
}