<?php  // *** DO NOT EDIT THIS FILE, CREATE A COPY !!

/**
 * (Popup) Gallery layout  --  GLightbox
 *
 * This layout supports inline_info, pretext, posttext
 */

// ***
// *** Load per-field parameters (only once per field)
// ***

// Flexi stores yes/no layout params as the strings "true"/"false", never as ints,
// so we must parse them (a bare (int) cast would turn "true" into 0)
if ( !function_exists('fc_glight_yn') )
{
	function fc_glight_yn($v, $default = 0)
	{
		$v = $v === null ? $default : $v;
		if (is_bool($v)) return (int) $v;
		if (is_string($v))
		{
			if ($v === 'true'  || $v === '1') return 1;
			if ($v === 'false' || $v === '0') return 0;
		}
		return (int) $v;
	}
}

// "Display caption in lightbox" is a GLightbox layout param, fully independent from the
// field's general "show title / show description" (showtitle/showdesc) which only control
// the inline info box rendered below each thumbnail inside the page
$PPFX_show_caption    = fc_glight_yn( $field->parameters->get( $PPFX_ . 'show_caption', 'true' ), 1 );

// Which resized image is opened in the lightbox (s/m/l/o), independent from the size shown in the view
$open_size = $field->parameters->get( $PPFX_ . 'open_size', 'l' );

// Caption position of THIS field's gallery; it is passed per-slide via the data-desc-position
// attribute because on a page with several GLightbox galleries a single JS instance is used,
// its global descPosition would otherwise be the one of the FIRST field rendered only
$desc_position = $field->parameters->get( $PPFX_ . 'desc_position', 'bottom' );

// Decode HTML entities until the string is stable: handles values stored already encoded once or
// several times (repeated saves through Joomla's InputFilter)
if ( !function_exists('fc_glight_decode_until_stable') )
{
	function fc_glight_decode_until_stable($s)
	{
		$prev = '';
		$cur  = (string) $s;
		for ($i = 0; $i < 4 && $cur !== $prev; $i++)
		{
			$prev = $cur;
			$cur  = html_entity_decode($cur, ENT_QUOTES, 'UTF-8');
		}
		return $cur;
	}
}

// ***
// *** Values loop
// ***

$i = -1;
foreach ($values as $n => $value)
{
	// Include common layout code for preparing values, but you may copy here to customize
	$result = include( JPATH_ROOT . '/plugins/flexicontent_fields/image/tmpl_common/prepare_value_display.php' );
	if ($result === _FC_CONTINUE_) continue;
	if ($result === _FC_BREAK_) break;

	// Un seul GLightbox par page : chaque vignette doit donc TOUJOURS porter un data-gallery
	// (celui du groupe courant, ou sinon le groupe de ce champ+item) pour rester isole des autres galeries
	$group_str   = 'data-gallery="' . ($group_name ?: ('fcview_' . $view . '_fcitem_' . $item->id . '_fcfield_' . $field->id)) . '"';
	$legend_icon = '';

	$caption_str = '';
	if ($PPFX_show_caption)
	{
		// Flexi stocke le desc/titre passés par dataFilter() (InputFilter Joomla) : le contenu peut
		// être encodé 1..N fois (sauvegardes répétées). On décode jusqu'à stabilité puis on encode
		// UNE seule fois pour l'attribut ; le navigateur redécode l'attribut et GLightbox l'injecte
		// via innerHTML, ainsi les balises comme <br /> sont rendues au lieu d'être affichées en texte.
		$_glight_title = nl2br(fc_glight_decode_until_stable((string) $title));
		$_glight_desc  = nl2br(fc_glight_decode_until_stable((string) $desc));
		$caption_str   = ' data-title="' . htmlspecialchars($_glight_title, ENT_COMPAT, 'UTF-8') . '"'
			. ' data-description="' . htmlspecialchars($_glight_desc, ENT_COMPAT, 'UTF-8') . '"';
	}

	if (!empty($usemediaurl) && !empty($value['mediaurl']))
	{
		$attribs = 'href="' . $value['mediaurl'] . '"  ';

		// Video providers natively supported by this JS gallery
		if (strpos($value['mediaurl'], 'youtube') !== false || strpos($value['mediaurl'], 'vimeo') !== false)
		{
			$style .= 'position: relative; display: inline-block;';
			$legend_icon = '<span class="fc-centered-icon-box"><span class="icon-video-2"></span></span>';
		}

		// Non video URL or a video provider not supported natively by this JS gallery
		else
		{
			$attribs .= ' data-type="iframe"';
		}
	}
	else
	{
		// Which image size to open in the lightbox: s, m, l or o (original)
		switch ($open_size)
		{
			case 's':
				$modal_src       = $abs_srcs;
				$modal_src_webp  = $abs_srcs_webp;
				$modal_webp_ok   = $webp_exists_s;
				$modal_w         = !empty($size_w_s) ? (int) $size_w_s : (int) $field->parameters->get('w_s', 120);
				break;
			case 'm':
				$modal_src       = $abs_srcm;
				$modal_src_webp  = $abs_srcm_webp;
				$modal_webp_ok   = $webp_exists_m;
				$modal_w         = !empty($size_w_m) ? (int) $size_w_m : (int) $field->parameters->get('w_m', 800);
				break;
			case 'o':
				$modal_src       = $abs_srco;
				$modal_src_webp  = '';
				$modal_webp_ok   = false;
				$modal_w         = 0;
				break;
			default: // 'l'
				$modal_src       = $abs_srcl;
				$modal_src_webp  = $abs_srcl_webp;
				$modal_webp_ok   = $webp_exists_l;
				$modal_w         = !empty($size_w_l) ? (int) $size_w_l : (int) $field->parameters->get('w_l', 800);
				break;
		}

		// Href pointe vers l'image choisie (fallback universel)
		$attribs = 'href="' . $modal_src . '" ';

		// WebP : GLightbox n'applique le srcset que si data-srcset ET data-sizes sont présents,
		// le srcset image remplace href chez les navigateurs supportant WebP, sinon on retombe sur href
		if (!empty($modal_src_webp) && $modal_webp_ok)
		{
			$attribs .= 'data-srcset="' . $modal_src_webp . ' ' . $modal_w . 'w" data-sizes="100vw" ';
		}
	}

$field->{$prop}[] = $pretext.
	'<a style="' . $style . '" ' . $attribs . ' class="fc_image_thumb glightbox_fc_' . $field->id . ' fc_glightbox" ' . $group_str . ' data-desc-position="' . $desc_position . '"' . $caption_str . '>
			' . $img_legend . '
			' . $legend_icon . '
		</a>'
		. $inline_info
		. $posttext;
}


// ***
// *** Add per page custom JS (ONE single GLightbox instance for all the page's galleries)
// ***
// GLightbox build() grabs the container by id "glightbox-body"; multiple instances on the same
// page would cross-contaminate each other's DOM, so we use a single instance whose elements are
// all .fc_glightbox anchors, and let the data-gallery attribute isolate each field's/item's gallery.

if ( !isset(static::$js_added['glightbox'][__FILE__]) )
{
	flexicontent_html::loadFramework('glightbox');

	$loop             = fc_glight_yn( $field->parameters->get( $PPFX_ . 'loop_mode', 'false' ), 0 );
	$keyboard         = fc_glight_yn( $field->parameters->get( $PPFX_ . 'keyboard_mode', 'true' ), 1 );
	$touch            = fc_glight_yn( $field->parameters->get( $PPFX_ . 'touch_navigation', 'true' ), 1 );
	$open_effect      = $field->parameters->get( $PPFX_ . 'open_effect', 'zoom' );
	$close_effect     = $field->parameters->get( $PPFX_ . 'close_effect', 'zoom' );
	$slide_effect     = $field->parameters->get( $PPFX_ . 'slide_effect', 'slide' );
	$close_outside    = fc_glight_yn( $field->parameters->get( $PPFX_ . 'close_outside', 'true' ), 1 );
	$zoomable         = fc_glight_yn( $field->parameters->get( $PPFX_ . 'zoomable', 'true' ), 1 );
	$draggable        = fc_glight_yn( $field->parameters->get( $PPFX_ . 'draggable', 'true' ), 1 );
	$preload          = fc_glight_yn( $field->parameters->get( $PPFX_ . 'preload', 'true' ), 1 );
	$autoplay_videos  = fc_glight_yn( $field->parameters->get( $PPFX_ . 'autoplay_videos', 'false' ), 0 );

	// Note: $desc_position is read above (top of file) and set per-slide via data-desc-position;
	// the global descPosition below is only a fallback for slides without the attribute

	$js = "
	(function() {
		function fcGlightboxInit() {
			if (typeof window.GLightbox === 'undefined') {
				window.setTimeout(fcGlightboxInit, 100);
				return;
			}
			GLightbox({
				selector: '.fc_glightbox',
				loop: " . ($loop ? 'true' : 'false') . ",
				keyboardNavigation: " . ($keyboard ? 'true' : 'false') . ",
				touchNavigation: " . ($touch ? 'true' : 'false') . ",
				openEffect: '" . addslashes($open_effect) . "',
				closeEffect: '" . addslashes($close_effect) . "',
				slideEffect: '" . addslashes($slide_effect) . "',
				closeOnOutsideClick: " . ($close_outside ? 'true' : 'false') . ",
				zoomable: " . ($zoomable ? 'true' : 'false') . ",
				draggable: " . ($draggable ? 'true' : 'false') . ",
				preload: " . ($preload ? 'true' : 'false') . ",
				autoplayVideos: " . ($autoplay_videos ? 'true' : 'false') . ",
				descPosition: '" . addslashes($desc_position) . "'
			});
		}
		if (document.readyState === 'complete' || document.readyState === 'interactive') fcGlightboxInit();
		else document.addEventListener('DOMContentLoaded', fcGlightboxInit);
	})();
	";

	\Joomla\CMS\Factory::getDocument()->addScriptDeclaration($js);

	static::$js_added['glightbox'][__FILE__] = array();
}


/**
 * Include common layout code before finalize values
 */

$result = include( JPATH_ROOT . '/plugins/flexicontent_fields/image/tmpl_common/before_values_finalize.php' );
if ($result !== _FC_RETURN_)
{
	// ***
	// *** Add container HTML (if required by current layout) and add value separator (if supported by current layout), then finally apply open/close tags
	// ***

	// Add value separator
	$field->{$prop} = implode($separatorf, $field->{$prop});

	$field->{$prop} = '
		<div class="glightbox_fccontainer_' . $field->id . '">
			' . $field->{$prop} . '
		</div>
	';

	// Apply open/close tags
	$field->{$prop}  = $opentag . $field->{$prop} . $closetag;
}