<?php  // *** DO NOT EDIT THIS FILE, CREATE A COPY !!

/**
 * (Popup) Gallery layout  --  Juxtapose
 *
 * This layout supports inline_info, pretext, posttext
 */


// ***
// *** Values loop
// ***

$i = -1;
$compositeKey='';
foreach ($values as $n => $value)
{
	// Include common layout code for preparing values, but you may copy here to customize
	$result = include( JPATH_ROOT . '/plugins/flexicontent_fields/image/tmpl_common/prepare_value_display.php' );
	if ($result === _FC_CONTINUE_) continue;
	if ($result === _FC_BREAK_) break;
	
	$field->{$prop}[] = $pretext . $img_legend . $inline_info . $posttext;
	$compositeKey.=$n.' ';
	if ($i%2 == 1) {
	$field->{$prop}.= 'code avant'. $field->{$prop}. 'code apres';
	}
	$i++;
}

var_dump($field->{$prop});

// ***
// *** Add per field custom JS
// ***

if ( !isset(static::$js_added[$field->id][__FILE__]) )
{
	//flexicontent_html::loadFramework('juxtapose'); TODO ADDING script inline not in CDN

	$js = '';

	if ($js) JFactory::getDocument()->addScriptDeclaration($js);

	static::$js_added[$field->id][__FILE__] = array();
}

// ***
// *** Add - per (field, item) pair - custom JS
// ***

$uid = 'fc_'.$field_name_js."_fcitem".$item->id;

if (!isset(static::$js_added[$field->id][__FILE__][$item->id]))
{
	//$js = file_get_contents(JPATH_SITE.DS.'components'.DS.'com_flexicontent'.DS.'librairies'.DS.'fancybox'.DS.'dist'.DS.'jquery.fancybox.js');
	//$js = str_replace('unique_gal_id', $uid, $js);



		//TODO render json format for button buttons: ["zoom","share","slideShow","fullScreen","download","thumbs","close"],

	$compare_mode      	  = $field->parameters->get( $PPFX_ . 'compare_mode', 'horizontal' ); // horizontal slide or vertical
	$slider_position      = $field->parameters->get( $PPFX_ . 'slider_position', '50' ); //starting position of slider
	$display_label       = $field->parameters->get( $PPFX_ . 'display_label', 'true' ); //display label
	$display_credit     = $field->parameters->get( $PPFX_ . 'display_credit', 'true' ); //display credit
	$use_animation    = $field->parameters->get( $PPFX_ . 'use_animation', 'true' ); //disable animation
	$make_responsive    = $field->parameters->get( $PPFX_ . 'make_responsive', 'true' ); //disable responsive image

	$js = "
	(function($)
	{
		$(document).ready(function()
		{
			var juxtapose = $('.juxtapose');

			juxtapose.each(function(index, element) {
			var juxtaposeContainer = juxtapose.parent();
			var juxtaposeRatio;
		
			$(window).on('load', function (event) {
				juxtaposeRatio = $(element).outerHeight() / $(element).outerWidth();
			});
		
			$(window).on('resize', function (event) {
				var newWidth = juxtaposeContainer.outerWidth();
				var newHeight = newWidth * juxtaposeRatio;
				$(element).css({width: newWidth, height: newHeight});
			});
		});
	});
})(jQuery);
	";

	if ($js) JFactory::getDocument()->addScriptDeclaration($js);
	static::$js_added[$field->id][__FILE__][$item->id] = true;
}

/**
 * Include common layout code before finalize values
 */

$result = include( JPATH_ROOT . '/plugins/flexicontent_fields/image/tmpl_common/before_values_finalize.php' );
if ($result !== _FC_RETURN_)
{
	// ***
	// *** Add container HTML (if required by current layout) and add value separator (if supported by current layout), then finally apply open/close tags
	// ***

	// Add value separator
	$field->{$prop} = implode($separatorf, $field->{$prop});

	$field->{$prop} = '
		<div id="juxtapose-wrapper" class="juxtapose" data-startingposition="'.$slider_position.'%" data-showlabels="'.$display_label .'" data-showcredits="'.$display_credit.'" data-makeresponsive="'.$make_responsive.'" data-mode="'.$compare_mode.'" data-animate="'.$use_animation.'">
			
				' . $field->{$prop} . '
			
		</div>
		<script src="https://cdn.knightlab.com/libs/juxtapose/latest/js/juxtapose.min.js"></script>
<link rel="stylesheet" href="https://cdn.knightlab.com/libs/juxtapose/latest/css/juxtapose.css">
	';

	// Apply open/close tags
	$field->{$prop}  = $opentag . $field->{$prop} . $closetag;
}
