<?php  // *** DO NOT EDIT THIS FILE, CREATE A COPY !!

/**
 * (Popup) Gallery layout  --  Fancybox
 *
 * This layout supports inline_info, pretext, posttext
 */


// ***
// *** Values loop
// ***

$i = -1;
foreach ($values as $n => $value)
{
	// Include common layout code for preparing values, but you may copy here to customize
	$result = include( JPATH_ROOT . '/plugins/flexicontent_fields/image/tmpl_common/prepare_value_display.php' );
	if ($result === _FC_CONTINUE_) continue;
	if ($result === _FC_BREAK_) break;

	$title_attr = htmlspecialchars($desc ? '<b>' . $title . '</b><br> ' . $desc : $title, ENT_COMPAT, 'UTF-8');
	$group_str = $group_name ? 'data-fancybox="' . $group_name . '"' : '';
	$legend_icon = '';

	if (!empty($usemediaurl) && !empty($value['mediaurl']))
	{
		$attribs = 'href="' . $value['mediaurl'] . '"  ';

		// Video providers natively supported by this JS gallery
		if (strpos($value['mediaurl'], 'youtube') !== false || strpos($value['mediaurl'], 'vimeo') !== false)
		{
			$style .= 'position: relative; display: inline-block;';
			$legend_icon = '<span class="fc-centered-icon-box"><span class="icon-video-2"></span></span>';
		}

		// Non video URL or a video provider not supported nativley by this JS gallery
		else
		{
			$attribs .= ' data-type="iframe"';
		}
	}
	else
	{
		// Href pointe vers le JPEG large (fallback universel)
		$attribs = 'href="' . \Joomla\CMS\Uri\Uri::root(true).'/'.$srcl . '" ';

		// Option B : si WebP large existe sur disque, l'ajouter en data-src pour Fancybox 3+
		// Fancybox utilise data-src en priorité sur href — les vieux navigateurs tombent sur href JPEG
		if (!empty($srcl_webp))
		{
			$_srcl_webp_rel  = ltrim(str_replace(\Joomla\CMS\Uri\Uri::root(), '', $abs_srcl_webp), '/');
			$_srcl_webp_rel  = $_srcl_webp_rel ?: ltrim(str_replace(\Joomla\CMS\Uri\Uri::root(true).'/', '', $abs_srcl_webp), '/');
			$_srcl_webp_disk = JPATH_SITE . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $_srcl_webp_rel);
			if (file_exists($_srcl_webp_disk))
			{
				$attribs .= 'data-src="' . \Joomla\CMS\Uri\Uri::root(true).'/'.$srcl_webp . '" ';
			}
		}
	}

	$field->{$prop}[] = $pretext.
		'<a style="' . $style . '" ' . $attribs . ' class="fc_image_thumb fb_gallery" ' . $group_str . ' data-title="' . $title_attr . '" data-caption="' . $title_attr . '">
			' . $img_legend . '
			' . $legend_icon . '
		</a>'
		. $inline_info
		. $posttext;
}



// ***
// *** Add per field custom JS
// ***

if ( !isset(static::$js_added[$field->id][__FILE__]) )
{
	// In Choices.js mode the front is jQuery-free: use a self-contained vanilla lightbox
	// instead of the jQuery fancybox library.
	$gallery_cparams = \Joomla\CMS\Component\ComponentHelper::getParams('com_flexicontent');
	$gallery_useChoices = (int) $gallery_cparams->get('select_lib_type', 0) === 1;

	if ($gallery_useChoices)
	{
		$js = '
		(function() {
			var fcLightbox = window.fcLightbox || null;
			if (fcLightbox) return;
			window.fcLightbox = true;

			function fcLightboxInit() {
			var CSS = "div.fc-lightbox{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.9);z-index:99999;display:none;align-items:center;justify-content:center;flex-direction:column}div.fc-lightbox.fc-is-open{display:flex}div.fc-lightbox img,div.fc-lightbox iframe{max-width:92vw;max-height:84vh;box-shadow:0 0 25px rgba(0,0,0,.6)}div.fc-lightbox .fc-lightbox-media{display:flex;align-items:center;justify-content:center}div.fc-lightbox button{position:absolute;background:rgba(0,0,0,.5);color:#fff;border:0;font-size:28px;line-height:1;cursor:pointer;padding:2px 10px}div.fc-lightbox .fc-lb-close{top:12px;right:12px}div.fc-lightbox .fc-lb-prev{left:12px;top:50%;transform:translateY(-50%)}div.fc-lightbox .fc-lb-next{right:12px;top:50%;transform:translateY(-50%)}div.fc-lightbox .fc-lb-caption{color:#fff;padding:10px;text-align:center}";
			(function(){var s=document.createElement("style");s.textContent=CSS;document.head.appendChild(s);})();

			var overlay = document.createElement("div");
			overlay.className = "fc-lightbox";
			overlay.innerHTML = "<button type=button class=fc-lb-close>&times;</button><button type=button class=fc-lb-prev>&lsaquo;</button><div class=fc-lightbox-media></div><button type=button class=fc-lb-next>&rsaquo;</button><div class=fc-lb-caption></div>";
			document.body.appendChild(overlay);

			var media = overlay.querySelector(".fc-lightbox-media");
			var caption = overlay.querySelector(".fc-lb-caption");
			var items = [];
			var idx = 0;

			function isVideo(url){ return /youtube\.com\/watch\?v=|youtu\.be\/|vimeo\.com\//.test(url); }
			function buildSrc(el){
				var href = el.getAttribute("href") || el.getAttribute("data-src") || "";
				if (el.getAttribute("data-type") === "iframe" || isVideo(href)) {
					if (/youtube\.com\/watch\?v=([\w-]+)/.test(href)) {
						var m = href.match(/youtube\.com\/watch\?v=([\w-]+)/);
						return { type: "iframe", src: "https://www.youtube.com/embed/" + m[1] };
					}
					if (/youtu\.be\/([\w-]+)/.test(href)) {
						var m2 = href.match(/youtu\.be\/([\w-]+)/);
						return { type: "iframe", src: "https://www.youtube.com/embed/" + m2[1] };
					}
					if (/vimeo\.com\/(\d+)/.test(href)) {
						var m3 = href.match(/vimeo\.com\/(\d+)/);
						return { type: "iframe", src: "https://player.vimeo.com/video/" + m3[1] };
					}
					return { type: "iframe", src: href };
				}
				return { type: "img", src: el.getAttribute("data-src") || href };
			}

			function render(){
				media.innerHTML = "";
				var g = items[idx];
				if (!g) return;
				if (g.type === "iframe") {
					var f = document.createElement("iframe");
					f.src = g.src; f.setAttribute("allowfullscreen","");
					f.setAttribute("frameborder","0");
					f.setAttribute("allow","autoplay; fullscreen; encrypted-media");
					media.appendChild(f);
				} else {
					var im = document.createElement("img");
					im.src = g.src;
					media.appendChild(im);
				}
				caption.textContent = g.title || "";
				overlay.style.display = "flex";
				document.body.style.overflow = "hidden";
			}

			function close(){ overlay.style.display = "none"; media.innerHTML = ""; document.body.style.overflow = ""; }
			function nav(dir){ idx = (idx + dir + items.length) % items.length; render(); }

			overlay.querySelector(".fc-lb-close").addEventListener("click", close);
			overlay.querySelector(".fc-lb-prev").addEventListener("click", function(){ nav(-1); });
			overlay.querySelector(".fc-lb-next").addEventListener("click", function(){ nav(1); });
			overlay.addEventListener("click", function(e){ if (e.target === overlay) close(); });
			document.addEventListener("keydown", function(e){
				if (overlay.style.display === "none") return;
				if (e.key === "Escape") close();
				if (e.key === "ArrowLeft") nav(-1);
				if (e.key === "ArrowRight") nav(1);
			});

			document.addEventListener("click", function(e){
				var a = e.target.closest ? e.target.closest("a.fb_gallery") : null;
				if (!a) return;
				e.preventDefault();
				var gal = (a.dataset && a.dataset.fancybox) || (a.getAttribute && a.getAttribute("data-fancybox")) || "";
				var groupEls, i;
				if (gal) {
					groupEls = Array.prototype.slice.call(document.querySelectorAll("a.fb_gallery[data-fancybox=\"" + gal + "\"]"));
				} else {
					groupEls = [a];
				}
				items = groupEls.map(function(x){
					var s = buildSrc(x);
					s.title = x.getAttribute("data-title") || "";
					return s;
				});
				idx = groupEls.indexOf(a);
				if (idx < 0) idx = 0;
				render();
			});
			}

			if (document.body) {
				fcLightboxInit();
			} else {
				document.addEventListener("DOMContentLoaded", fcLightboxInit);
			}
		})();
		';
	}
	else
	{
		flexicontent_html::loadFramework('fancybox');
		$js = '';
	}

	if ($js) \Joomla\CMS\Factory::getDocument()->addScriptDeclaration($js);

	static::$js_added[$field->id][__FILE__] = array();
}

// ***
// *** Add - per (field, item) pair - custom JS
// ***

$uid = 'fc_'.$field_name_js."_fcitem".$item->id;

if (!isset(static::$js_added[$field->id][__FILE__][$item->id]))
{
	// In Choices.js mode (jQuery-free front) the vanilla lightbox binds itself to all
	// a.fb_gallery links generically, so no per-field jQuery fancybox init is emitted.
	$gallery_cparams2 = \Joomla\CMS\Component\ComponentHelper::getParams('com_flexicontent');
	$gallery_useChoices2 = (int) $gallery_cparams2->get('select_lib_type', 0) === 1;

	if ($gallery_useChoices2)
	{
		static::$js_added[$field->id][__FILE__][$item->id] = true;
	}
	else
	{
		//$js = file_get_contents(JPATH_SITE.DS.'components'.DS.'com_flexicontent'.DS.'librairies'.DS.'fancybox'.DS.'dist'.DS.'jquery.fancybox.js');
		//$js = str_replace('unique_gal_id', $uid, $js);



		//TODO render json format for button buttons: ["zoom","share","slideShow","fullScreen","download","thumbs","close"],

	$display_infobar      = $field->parameters->get( $PPFX_ . 'diplay_infobar', 'true' );
	$display_toolbar      = $field->parameters->get( $PPFX_ . 'diplay_toolbar', 'auto' );
	$display_thumbs       = $field->parameters->get( $PPFX_ . 'diplay_thumbs_autostart', 'false' );
	$animation_effect     = $field->parameters->get( $PPFX_ . 'animation_effect', 'zoom' );
	$animation_duration   = (int) $field->parameters->get( $PPFX_ . 'animation_duration', 400 );
	$transition_effect    = $field->parameters->get( $PPFX_ . 'transition_effect', 'fade' );
	$transition_duration  = (int) $field->parameters->get( $PPFX_ . 'transition_duration', 400 );
	$loop                 = $field->parameters->get( $PPFX_ . 'loop_mode', 'false' );
	$keyboard             = $field->parameters->get( $PPFX_ . 'keyboard_mode', 'true' );
	$image_protect        = $field->parameters->get( $PPFX_ . 'protect_image', 'true' );
	$slideshow_autostart  = $field->parameters->get( $PPFX_ . 'slideshow_autostart', 'false' );
	$slideshow_speed      = (int) $field->parameters->get( $PPFX_ . 'slideshow_speed', 3000 );
	$buttons_shown        = $field->parameters->get( $PPFX_ . 'buttons_shown', array('zoom','share','slideShow','fullScreen','download','thumbs','close') );

	$js = "
	(function($)
	{
		$(document).ready(function()
		{
			$('#fb_gallery_" . $uid . " a.fb_gallery').fancybox({
				loop: $loop,
				keyboard: $keyboard,
				infobar: $display_infobar,
				toolbar: '$display_toolbar',
				button : " . '["' . implode('","', $buttons_shown ) . '"]' . ",
				protect: $image_protect,
				animationEffect: '$animation_effect',
				animationDuration: $animation_duration,
				transitionEffect: '$transition_effect',
				transitionDuration: $transition_duration,
				slideShow: {autoStart: $slideshow_autostart,speed: $slideshow_speed}
			});
		});
	})(jQuery);
	";

	if ($js) \Joomla\CMS\Factory::getDocument()->addScriptDeclaration($js);
		static::$js_added[$field->id][__FILE__][$item->id] = true;
	}
}

/**
 * Include common layout code before finalize values
 */

$result = include( JPATH_ROOT . '/plugins/flexicontent_fields/image/tmpl_common/before_values_finalize.php' );
if ($result !== _FC_RETURN_)
{
	// ***
	// *** Add container HTML (if required by current layout) and add value separator (if supported by current layout), then finally apply open/close tags
	// ***

	// Add value separator
	$field->{$prop} = implode($separatorf, $field->{$prop});

	$field->{$prop} = '
		<div id="fb_gallery_' . $uid . '">
			' . $field->{$prop} . '
		</div>
	';

	// Apply open/close tags
	$field->{$prop}  = $opentag . $field->{$prop} . $closetag;
}
