<?php  // *** DO NOT EDIT THIS FILE, CREATE A COPY !!

/**
 * (Inline) Gallery layout  --  Swiper.js + GLightbox
 *
 * Swiper.js  : carousel with thumbnail navigation (vanilla JS, MIT)
 * GLightbox  : lightbox popup on click of the main image (vanilla JS, MIT)
 *
 * This layout supports inline_info, pretext, posttext
 */

// ***
// *** Load per-field parameters (only once per field)
// ***

// Helper: parse Flexi yes/no string params
if ( !function_exists('fc_swiper_yn') )
{
	function fc_swiper_yn($v, $default = 0)
	{
		$v = $v === null ? $default : $v;
		if (is_bool($v)) return (int) $v;
		if (is_string($v))
		{
			if ($v === 'true'  || $v === '1') return 1;
			if ($v === 'false' || $v === '0') return 0;
		}
		return (int) $v;
	}
}

// Swiper carousel parameters
$autoplay        = fc_swiper_yn( $field->parameters->get( $PPFX_.'autoplay', 'false' ), 0 );
$autoplay_delay  = (int) $field->parameters->get( $PPFX_.'autoplay_delay', 3000 );
$loop            = fc_swiper_yn( $field->parameters->get( $PPFX_.'loop_mode', 'false' ), 0 );
$rewind          = fc_swiper_yn( $field->parameters->get( $PPFX_.'rewind', 'false' ), 0 );
$speed           = (int) $field->parameters->get( $PPFX_.'speed', 300 );
$show_pagination = fc_swiper_yn( $field->parameters->get( $PPFX_.'show_pagination', 'true' ), 1 );
$pag_type         = $field->parameters->get( $PPFX_.'pagination_type', 'bullets' );
$pag_clickable    = fc_swiper_yn( $field->parameters->get( $PPFX_.'pagination_clickable', 'true' ), 1 );
$pag_dynamic      = fc_swiper_yn( $field->parameters->get( $PPFX_.'pagination_dynamic', 'false' ), 0 );
$pag_hideonclick  = fc_swiper_yn( $field->parameters->get( $PPFX_.'pagination_hideonclick', 'false' ), 0 );
$pag_fraction     = $field->parameters->get( $PPFX_.'pagination_fraction', '{current} / {total}' );
$accent_color     = trim( $field->parameters->get( $PPFX_.'accent_color', '' ) );

// Accent color: only accept a valid hex color
if ($accent_color && !preg_match('/^#[0-9a-fA-F]{6}$/', $accent_color))
{
	$accent_color = '';
}
$nav_color        = trim( $field->parameters->get( $PPFX_.'nav_color', '' ) );
if ($nav_color && !preg_match('/^#[0-9a-fA-F]{6}$/', $nav_color))
{
	$nav_color = '';
}
$nav_color = $nav_color ?: $accent_color;
$show_nav        = fc_swiper_yn( $field->parameters->get( $PPFX_.'show_nav', 'true' ), 1 );
$show_thumbs     = fc_swiper_yn( $field->parameters->get( $PPFX_.'show_thumbs', 'true' ), 1 );
$swiper_thumb_size = $field->parameters->get( $PPFX_.'thumb_size', 'm' );
$thumb_custom_w  = (int) $field->parameters->get( $PPFX_.'thumb_custom_size', 0 );
$thumb_height    = (int) $field->parameters->get( $PPFX_.'thumb_height', 80 );
$thumb_position  = $field->parameters->get( $PPFX_.'thumb_position', 'below' );
if (!in_array($thumb_position, array('above','left','right'))) $thumb_position = 'below';
$thumb_is_vertical = in_array($thumb_position, array('left','right'));
$slide_height    = trim( $field->parameters->get( $PPFX_.'slide_height', '' ) );
$slide_is_ratio  = $slide_height !== '' && strpos($slide_height, '/') !== false;
$slide_css_value = $slide_is_ratio ? $slide_height : ((int) $slide_height ? (int) $slide_height . 'px' : '');
$image_fit    = $field->parameters->get( $PPFX_.'image_fit', 'cover' );
if (!in_array($image_fit, array('cover', 'contain'))) $image_fit = 'cover';
$carousel_padding = trim( $field->parameters->get( $PPFX_.'carousel_padding', '' ) );
if ($carousel_padding !== '' && !preg_match('/^(\d+(\.\d+)?[a-z%]*)(\s+(\d+(\.\d+)?[a-z%]*)){0,3}$/i', $carousel_padding)) $carousel_padding = '';

// Swiper behavior parameters
$direction      = $field->parameters->get( $PPFX_.'direction', 'horizontal' );
$effect         = $field->parameters->get( $PPFX_.'effect', 'slide' );
$cube_shadow          = fc_swiper_yn( $field->parameters->get( $PPFX_.'cube_shadow', 'true' ), 1 );
$flip_limit_rotation  = fc_swiper_yn( $field->parameters->get( $PPFX_.'flip_limit_rotation', 'true' ), 1 );
$cards_rotate         = fc_swiper_yn( $field->parameters->get( $PPFX_.'cards_rotate', 'true' ), 1 );
$cards_per_slide_offset = (float) $field->parameters->get( $PPFX_.'cards_per_slide_offset', 8 );
$cards_per_slide_rotate = (float) $field->parameters->get( $PPFX_.'cards_per_slide_rotate', 2 );
$slide_shadows        = fc_swiper_yn( $field->parameters->get( $PPFX_.'slide_shadows', 'true' ), 1 );
$coverflow_rotate  = (int) $field->parameters->get( $PPFX_.'coverflow_rotate', 50 );
$coverflow_stretch = (int) $field->parameters->get( $PPFX_.'coverflow_stretch', 0 );
$coverflow_depth   = (int) $field->parameters->get( $PPFX_.'coverflow_depth', 100 );
$coverflow_scale   = (float) $field->parameters->get( $PPFX_.'coverflow_scale', 1 );
$space_between  = (int) $field->parameters->get( $PPFX_.'space_between', 10 );
$centered       = fc_swiper_yn( $field->parameters->get( $PPFX_.'centered_slides', 'false' ), 0 );
$slides_per_view  = $field->parameters->get( $PPFX_.'slides_per_view', '1' );
$slides_per_group = $field->parameters->get( $PPFX_.'slides_per_group', '1' );
$grid_rows        = (int) $field->parameters->get( $PPFX_.'grid_rows', 1 );
$grid_fill        = $field->parameters->get( $PPFX_.'grid_fill', 'row' );
$responsive_spv   = fc_swiper_yn( $field->parameters->get( $PPFX_.'responsive_spv', 'false' ), 0 );
$spv_tablet       = $responsive_spv ? (string) $field->parameters->get( $PPFX_.'slides_per_view_tablet', '1' ) : '';
$spv_phone        = $responsive_spv ? (string) $field->parameters->get( $PPFX_.'slides_per_view_phone', '1' ) : '';

// Swiper limitations:
// - Fade/Cube/Flip always display ONE slide at a time (slides per view is
//   forced to 1, Swiper clamps it internally too). Coverflow AND Cards accept
//   several slides per view (Cards shows a visible stack behind the active one).
// - The multi-row grid layout works with the 'slide', the 'fade' and the 'flip'
//   (a column of N rows that transitions page by page), the 'coverflow' effect
//   (3D transforms per cell + pagination pages, validated headless) AND the
//   'cards' effect (cells of stacked cards, validated headless). Only the cube
//   effect renders broken cells in a grid, so grid stays forced to 1 for it.
// Force a valid state instead of rendering a broken gallery.
$single_slide_effect = in_array($effect, array('fade', 'cube', 'flip'));
$grid_supported      = in_array($effect, array('slide', 'fade', 'flip', 'coverflow', 'cards'));
if (!$grid_supported)
{
	$grid_rows = 1;
}
if ($single_slide_effect)
{
	$slides_per_view = '1';
	$responsive_spv  = 0;
	$spv_tablet      = '';
	$spv_phone       = '';
}
$grab_cursor    = fc_swiper_yn( $field->parameters->get( $PPFX_.'grab_cursor', 'false' ), 0 );
$keyboard       = fc_swiper_yn( $field->parameters->get( $PPFX_.'keyboard', 'false' ), 0 );
$mousewheel     = fc_swiper_yn( $field->parameters->get( $PPFX_.'mousewheel', 'false' ), 0 );

// Scrollbar options
$show_scrollbar      = fc_swiper_yn( $field->parameters->get( $PPFX_.'show_scrollbar', 'false' ), 0 );
$scrollbar_draggable = fc_swiper_yn( $field->parameters->get( $PPFX_.'scrollbar_draggable', 'true' ), 1 );
$scrollbar_hide      = fc_swiper_yn( $field->parameters->get( $PPFX_.'scrollbar_hide', 'false' ), 0 );
$scrollbar_drag_size = (int) $field->parameters->get( $PPFX_.'scrollbar_drag_size', 0 );

// Auto height: dynamically adjust carousel height to match active slide content
$auto_height = fc_swiper_yn( $field->parameters->get( $PPFX_.'auto_height', 'false' ), 0 );

// Vertical mode REQUIRES a defined container height (Swiper breaks otherwise) → fallback to a responsive 16/9 area
if (!$slide_css_value && $direction === 'vertical' && !$auto_height)
{
	$slide_css_value = '16/9';
	$slide_is_ratio  = true;
}

// Multi-row grid REQUIRES a defined wrapper height: Grid sets each slide height as a
// percentage of .swiper-wrapper (which is height:100%), so without a definite container
// height every image stacks in a single column (Swiper issues #5850, #7366).
// autoHeight (wrapper sized to one column) and loop mode are incompatible with grid rows.
if ($grid_rows > 1)
{
	$auto_height = 0;
	$loop        = 0;
	if (!$slide_css_value)
	{
		$slide_css_value = '16/9';
		$slide_is_ratio  = true;
	}
}

// Contain needs a defined cell area to letterbox around the image (object-fit).
// Without a height the cell grows to the image, so contain would render exactly
// like cover (image sized to 100% of the cell width). Force the same 16/9 area
// fallback as grid/vertical modes so the image stays whole, centered and not
// full-width. The explicit Auto height (PPFX_auto_height) keeps its variable
// height behaviour.
if ($image_fit === 'contain' && !$slide_css_value && !$auto_height)
{
	$slide_css_value = '16/9';
	$slide_is_ratio  = true;
}

// Auto height + explicit pixel carousel height → the fixed height is IGNORED by
// Swiper's autoHeight (the wrapper is sized to the active slide). Make it act as
// a CAP: images and the carousel never exceed it, smaller images keep their
// natural height (ratio-based heights can't be turned into a cap, so skipped).
$carousel_cap = ($auto_height && $slide_height !== '' && !$slide_is_ratio) ? (int) $slide_height : 0;

// GLightbox parameters
$open_size      = $field->parameters->get( $PPFX_.'open_size', 'l' );
$show_caption   = fc_swiper_yn( $field->parameters->get( $PPFX_.'show_caption', 'true' ), 1 );
$desc_position  = $field->parameters->get( $PPFX_.'desc_position', 'bottom' );
$glightbox_loop = fc_swiper_yn( $field->parameters->get( $PPFX_.'glightbox_loop', 'true' ), 1 );

// Decode HTML entities until the string is stable
if ( !function_exists('fc_swiper_decode_until_stable') )
{
	function fc_swiper_decode_until_stable($s)
	{
		$prev = '';
		$cur  = (string) $s;
		for ($i = 0; $i < 4 && $cur !== $prev; $i++)
		{
			$prev = $cur;
			$cur  = html_entity_decode($cur, ENT_QUOTES, 'UTF-8');
		}
		return $cur;
	}
}

// Unique ID for this gallery instance
$uid = 'fc_swiper_'.$field_name_js.'_fcitem'.$item->id;

// Thumbnails collected during the values loop (one <img> per image)
$swiper_thumbs = array();


// ***
// *** Values loop
// ***

$i = -1;
foreach ($values as $n => $value)
{
	// Include common layout code for preparing values
	$result = include( JPATH_ROOT . '/plugins/flexicontent_fields/image/tmpl_common/prepare_value_display.php' );
	if ($result === _FC_CONTINUE_) continue;
	if ($result === _FC_BREAK_) break;

	// Single GLightbox per page : every thumbnail must ALWAYS carry a data-gallery
	$group_str = 'data-gallery="' . ($group_name ?: ('fcview_'.$view.'_fcitem_'.$item->id.'_fcfield_'.$field->id)) . '"';

	// GLightbox caption data attributes
	$caption_str = '';
	if ($show_caption)
	{
		$_g_title = nl2br(fc_swiper_decode_until_stable((string) $title));
		$_g_desc  = nl2br(fc_swiper_decode_until_stable((string) $desc));
		$caption_str = ' data-title="' . htmlspecialchars($_g_title, ENT_COMPAT, 'UTF-8') . '"'
			. ' data-description="' . htmlspecialchars($_g_desc, ENT_COMPAT, 'UTF-8') . '"';
	}

	// Determine the image/video opened by GLightbox
	if (!empty($usemediaurl) && !empty($value['mediaurl']))
	{
		$modal_href    = $value['mediaurl'];
		$modal_attribs = '';
		if (strpos($value['mediaurl'], 'youtube') === false && strpos($value['mediaurl'], 'vimeo') === false)
		{
			$modal_attribs = ' data-type="iframe"';
		}
	}
	else
	{
		switch ($open_size)
		{
			case 's':
				$modal_src      = $abs_srcs;
				$modal_src_webp = $abs_srcs_webp;
				$modal_webp_ok  = $webp_exists_s;
				$modal_w        = !empty($size_w_s) ? (int) $size_w_s : (int) $field->parameters->get('w_s', 120);
				break;
			case 'm':
				$modal_src      = $abs_srcm;
				$modal_src_webp = $abs_srcm_webp;
				$modal_webp_ok  = $webp_exists_m;
				$modal_w        = !empty($size_w_m) ? (int) $size_w_m : (int) $field->parameters->get('w_m', 400);
				break;
			case 'o':
				$modal_src      = $abs_srco;
				$modal_src_webp = '';
				$modal_webp_ok  = false;
				$modal_w        = 0;
				break;
			default: // 'l'
				$modal_src      = $abs_srcl;
				$modal_src_webp = $abs_srcl_webp;
				$modal_webp_ok  = $webp_exists_l;
				$modal_w        = !empty($size_w_l) ? (int) $size_w_l : (int) $field->parameters->get('w_l', 800);
				break;
		}
		$modal_href    = $modal_src;
		$modal_attribs = '';
		if (!empty($modal_src_webp) && $modal_webp_ok)
		{
			$modal_attribs = ' data-srcset="' . $modal_src_webp . ' ' . $modal_w . 'w" data-sizes="100vw"';
		}
	}

	// Main carousel slide (clickable -> GLightbox)
	// Swiper uses translate3d, lazy-loaded images outside viewport never trigger → force eager
	$img_legend_eager = str_replace('loading="lazy"', 'loading="eager"', $img_legend);
	$field->{$prop}[] =
		'<div class="swiper-slide">'
			. '<a class="fc_glightbox" href="' . $modal_href . '" '
				. $modal_attribs . ' ' . $group_str . ' '
				. 'data-desc-position="' . $desc_position . '"' . $caption_str . '>'
				. $img_legend_eager
			. '</a>'
			. $inline_info
		. '</div>';

	// Thumbnail strip image (size based on parameter, WebP aware)
	if ($swiper_thumb_size === 'custom' && $thumb_custom_w > 0 && !$isURL)
	{
		// Runtime phpThumb: resize original image and cache for 30 days
		$thumb_src = \Joomla\CMS\Uri\Uri::root(true)
			. '/components/com_flexicontent/librairies/phpthumb/phpThumb.php?src='
			. rawurlencode('/' . ltrim($srco, '/'))
			. '&w=' . $thumb_custom_w . '&h=0&zc=0&q=85&ar=x&f=jpg';
	}
	else
	{
		// Pre-generated thumbnail: pick s, m, or l
		switch ($swiper_thumb_size)
		{
			case 's':  $thumb_src = $abs_srcs; break;
			case 'l':  $thumb_src = $abs_srcl; break;
			default:   $thumb_src = $abs_srcm; break;
		}
	}
	$swiper_thumbs[] =
		'<div class="swiper-slide">'
			. '<img src="' . $thumb_src . '" alt="' . $alt_encoded . '" '
				. 'loading="lazy" decoding="async" '
				. 'style="' . ($thumb_is_vertical
					? 'width:' . $thumb_height . 'px; height:auto;'
					: 'height:' . $thumb_height . 'px; width:auto;')
				. ' max-width:none; object-fit:cover; cursor:pointer;" />'
		. '</div>';
}


// ***
// *** Add per page custom JS (ONE Swiper init for ALL the page's galleries, ONE GLightbox)
// ***

if ( !isset(static::$js_added['swiper_glightbox'][__FILE__]) )
{
	flexicontent_html::loadFramework('swiper');
	flexicontent_html::loadFramework('glightbox');

	$js = "
	(function() {
		function fcSwiperGlightboxInit() {
			if (typeof window.Swiper === 'undefined' || typeof window.GLightbox === 'undefined') {
				window.setTimeout(fcSwiperGlightboxInit, 100);
				return;
			}

			// Single GLightbox instance for all galleries of the page,
			// data-gallery attribute isolates each field's / item's gallery
			GLightbox({
				selector: '.fc_glightbox',
				loop: " . ($glightbox_loop ? 'true' : 'false') . ",
				closeOnOutsideClick: true,
				zoomable: true,
				draggable: true,
				preload: true,
				descPosition: '" . addslashes($desc_position) . "'
			});

			// Initialize every Swiper gallery of the page from its data-* attributes
			document.querySelectorAll('.fc_swiper_container').forEach(function(container) {
				var mainEl  = container.querySelector('.fc_swiper_main');
				var thumbEl = container.querySelector('.fc_swiper_thumbs');
				if (!mainEl) return;

				var spaceValue = parseInt(container.getAttribute('data-space'), 10);
				var fx = container.getAttribute('data-effect') || 'slide';
				var mainParams = {
					spaceBetween: isNaN(spaceValue) ? 10 : spaceValue,
					speed: parseInt(container.getAttribute('data-speed') || '300', 10) || 300,
					observer: true,
					observeParents: false,
					watchOverflow: true,
					fitToWrapper: false,
					direction: container.getAttribute('data-direction') || 'horizontal',
					effect: fx
				};

				var spv = container.getAttribute('data-slides-per-view') || '1';
				var spvTablet = container.getAttribute('data-spv-tablet');
				var spvPhone = container.getAttribute('data-spv-phone');

				// Swiper limitation: fade/cube/flip only ever show ONE slide at a time
				// (cards shows a visible stack behind the active card, so it accepts slidesPerView > 1)
				if (fx === 'fade' || fx === 'cube' || fx === 'flip') {
					spv = '1';
					spvTablet = '';
					spvPhone = '';
				}

				// Effects with 3D slide shadows (generic option, Swiper defaults: ON) + their specific options
				var slideShadows = container.getAttribute('data-slide-shadows') !== '0';

				if (fx === 'cube') {
					mainParams.cubeEffect = {
						slideShadows: slideShadows,
						shadow: container.getAttribute('data-cube-shadow') !== '0'
					};
				}

				if (fx === 'flip') {
					mainParams.flipEffect = {
						slideShadows: slideShadows,
						limitRotation: container.getAttribute('data-flip-limit-rotation') !== '0'
					};
				}

				if (fx === 'cards') {
					var caOffset = parseInt(container.getAttribute('data-cards-per-slide-offset'), 10);
					var caRotate = parseInt(container.getAttribute('data-cards-per-slide-rotate'), 10);
					mainParams.cardsEffect = {
						slideShadows: slideShadows,
						rotate: container.getAttribute('data-cards-rotate') !== '0',
						perSlideOffset: isNaN(caOffset) ? 8 : caOffset,
						perSlideRotate: isNaN(caRotate) ? 2 : caRotate
					};
				}

				if (fx === 'coverflow') {
					var cfRotate  = parseInt(container.getAttribute('data-coverflow-rotate'), 10);
					var cfStretch = parseInt(container.getAttribute('data-coverflow-stretch'), 10);
					var cfDepth   = parseInt(container.getAttribute('data-coverflow-depth'), 10);
					var cfScale   = parseFloat(container.getAttribute('data-coverflow-scale'));
					mainParams.coverflowEffect = {
						slideShadows: slideShadows,
						rotate: isNaN(cfRotate) ? 50 : cfRotate,
						stretch: isNaN(cfStretch) ? 0 : cfStretch,
						depth: isNaN(cfDepth) ? 100 : cfDepth,
						scale: isNaN(cfScale) ? 1 : cfScale
					};
				}

				if (spvPhone || spvTablet) {
					mainParams.slidesPerView = spvPhone === 'auto' ? 'auto' : parseInt(spvPhone, 10) || 1;
					mainParams.breakpoints = {};
					if (spvTablet) {
						mainParams.breakpoints[768] = { slidesPerView: spvTablet === 'auto' ? 'auto' : parseInt(spvTablet, 10) || 1 };
					}
					mainParams.breakpoints[1200] = { slidesPerView: spv === 'auto' ? 'auto' : parseInt(spv, 10) || 1 };
				} else {
					mainParams.slidesPerView = spv === 'auto' ? 'auto' : parseInt(spv, 10) || 1;
				}

				var spg = container.getAttribute('data-slides-per-group') || '1';
				mainParams.slidesPerGroup = parseInt(spg, 10) || 1;

				if (container.getAttribute('data-auto-height') === '1') {
					mainParams.autoHeight = true;
				}

				if (container.getAttribute('data-centered') === '1') {
					mainParams.centeredSlides = true;
				}

				if (container.getAttribute('data-grab-cursor') === '1') {
					mainParams.grabCursor = true;
				}

				if (container.getAttribute('data-keyboard') === '1') {
					mainParams.keyboard = { enabled: true };
				}

				if (container.getAttribute('data-mousewheel') === '1') {
					mainParams.mousewheel = { forceToAxis: true };
				}

				if (container.getAttribute('data-loop') === '1') {
					mainParams.loop = true;
				}

				if (container.getAttribute('data-rewind') === '1') {
					mainParams.rewind = true;
				}

				// Grid layout is supported by the slide, fade, flip, coverflow and cards effects
				// (only cube renders broken cells in a grid)
				var gridRows = parseInt(container.getAttribute('data-grid-rows') || '1', 10) || 1;
				if (fx !== 'slide' && fx !== 'fade' && fx !== 'flip' && fx !== 'coverflow' && fx !== 'cards') {
					gridRows = 1;
				}
				if (gridRows > 1) {
					mainParams.grid = {
						rows: gridRows,
						fill: container.getAttribute('data-grid-fill') || 'row'
					};
					if (mainParams.slidesPerView === 'auto') {
						mainParams.slidesPerView = 1;
					}
				}

				if (container.getAttribute('data-autoplay') === '1') {
					mainParams.autoplay = {
						delay: parseInt(container.getAttribute('data-autoplay-delay') || '3000', 10) || 3000,
						disableOnInteraction: false
					};
				}

				if (container.getAttribute('data-pagination') === '1' && mainEl.querySelector('.swiper-pagination')) {
					var pagParams = {
						el: mainEl.querySelector('.swiper-pagination'),
						clickable: container.getAttribute('data-pag-clickable') === '1'
					};

					var pagType = container.getAttribute('data-pag-type') || 'bullets';
					if (pagType !== 'bullets') {
						pagParams.type = pagType;
					}

					if (pagType === 'bullets' && container.getAttribute('data-pag-dynamic') === '1') {
						pagParams.dynamicBullets = true;
					}

					if (pagType === 'fraction') {
						var fractionFormat = container.getAttribute('data-pag-fraction') || '{current} / {total}';
						pagParams.renderFraction = function(currentClass, totalClass) {
							return fractionFormat
								.replace(/\{current\}/g, '<span class=\"' + currentClass + '\"></span>')
								.replace(/\{total\}/g, '<span class=\"' + totalClass + '\"></span>');
						};
					}

					if (container.getAttribute('data-pag-hideonclick') === '1') {
						pagParams.hideOnClick = true;
					}

					mainParams.pagination = pagParams;
				}

				if (container.getAttribute('data-nav') === '1') {
					mainParams.navigation = {
nextEl: mainEl.querySelector('.swiper-button-next'),
					prevEl: mainEl.querySelector('.swiper-button-prev')
					};
				}

				if (container.getAttribute('data-scrollbar') === '1' && mainEl.querySelector('.swiper-scrollbar')) {
					var sbParams = {
						el: mainEl.querySelector('.swiper-scrollbar'),
						draggable: container.getAttribute('data-scrollbar-draggable') === '1',
						hide: container.getAttribute('data-scrollbar-hide') === '1'
					};
					var sbDragSize = parseInt(container.getAttribute('data-scrollbar-drag-size') || '0', 10) || 0;
					if (sbDragSize) {
						sbParams.dragSize = sbDragSize;
					}
					mainParams.scrollbar = sbParams;
				}

				// Thumbnails controller
				if (container.getAttribute('data-thumbs') === '1' && thumbEl) {
					var thumbParams = {
						spaceBetween: 8,
						slidesPerView: 'auto',
						freeMode: true,
						watchSlidesProgress: true
					};
					if (container.getAttribute('data-thumb-vertical') === '1') {
						thumbParams.direction = 'vertical';
						thumbParams.centeredSlides = true;
						thumbParams.centeredSlidesBounds = true;
					}
					var thumbSwiper = new Swiper(thumbEl, thumbParams);
					mainParams.thumbs = { swiper: thumbSwiper };
				}

				// Force all carousel images to load (Swiper uses translate3d, lazy images never trigger)
				container.querySelectorAll('.swiper-slide img[loading=\"lazy\"]').forEach(function(img) {
					img.removeAttribute('loading');
					if (!img.complete) { img.src = img.src; }
				});

				var swiper = new Swiper(mainEl, mainParams);
				container.querySelectorAll('.swiper-slide img').forEach(function(img) {
					if (!img.complete) {
						img.addEventListener('load', function() { swiper.update(); }, { once: true });
					}
				});
			});
		}

		if (document.readyState === 'complete' || document.readyState === 'interactive') fcSwiperGlightboxInit();
		else document.addEventListener('DOMContentLoaded', fcSwiperGlightboxInit);
	})();
	";

	\Joomla\CMS\Factory::getDocument()->addScriptDeclaration($js);

	static::$js_added['swiper_glightbox'][__FILE__] = array();
}


/**
 * Include common layout code before finalize values
 */

$result = include( JPATH_ROOT . '/plugins/flexicontent_fields/image/tmpl_common/before_values_finalize.php' );
if ($result !== _FC_RETURN_)
{
	// Add value separator
	$field->{$prop} = implode($separatorf, $field->{$prop});

	// Thumbnail strip HTML
	$thumbs_html = '';
	if ($show_thumbs && count($swiper_thumbs))
	{
		$thumb_cls    = 'swiper fc_swiper_thumbs' . ($thumb_is_vertical ? ' fc_swiper_thumbs_vertical' : '');
		$thumb_margin = $thumb_position === 'above' ? 'margin-bottom:10px;' : 'margin-top:10px;';
		$thumbs_html = '
		<div class="' . $thumb_cls . '" style="' . $thumb_margin . ' padding-bottom: 2px;">
			<div class="swiper-wrapper">
				' . implode('', $swiper_thumbs) . '
			</div>
		</div>';
	}

	$field->{$prop} = '
	<style>
		#' . $uid . ' { width: 100%; max-width: 100%; min-width: 0; overflow: hidden; }
		#flexicontent .flexi .flexi.element:has(> .flexi.value > #' . $uid . '),
		#flexicontent .flexi .flexi.element:has(> .flexi.value > #' . $uid . ') > .flexi.value { min-width: 0 !important; max-width: 100% !important; float: none !important; }
		#flexicontent .flexi .flexi.element:has(> .flexi.value > #' . $uid . ') > .flexi.value { display: block !important; width: 100% !important; padding: 0 !important; margin: 0 !important; }
		' . ($accent_color ? '#' . $uid . ' { --swiper-theme-color: ' . $accent_color . '; }' : '') . '
		#' . $uid . ' .fc_swiper_main .swiper-slide img,
		#' . $uid . ' .fc_swiper_main .swiper-slide picture img {
			max-width: 100%;
			height: auto;
			display: block;
			' . ($image_fit == 'contain' ? 'margin-left: auto; margin-right: auto;' : '') . '
		}' . ($carousel_cap ? '
		#' . $uid . ' .fc_swiper_main { max-height: ' . $carousel_cap . 'px; }
		#' . $uid . ' .fc_swiper_main .swiper-slide img,
		#' . $uid . ' .fc_swiper_main .swiper-slide picture img { width: auto; height: auto; max-width: 100% !important; max-height: ' . $carousel_cap . 'px; margin-left: auto; margin-right: auto; }' : '') . ($slide_css_value && !$auto_height ? '
		#' . $uid . ' .fc_swiper_main { ' . ($slide_is_ratio ? 'aspect-ratio: ' . $slide_css_value . ';' : 'height: ' . $slide_css_value . ';') . ' }
		#' . $uid . ' .fc_swiper_main .swiper-wrapper { height: 100%; }' . ($grid_rows <= 1 ? '
		#' . $uid . ' .fc_swiper_main .swiper-slide { height: 100%; }' : '') . ($image_fit == 'contain' ? '
		#' . $uid . ' .fc_swiper_main .swiper-slide > a { display: flex; align-items: center; justify-content: center; height: 100%; }
		#' . $uid . ' .fc_swiper_main .swiper-slide img,
		#' . $uid . ' .fc_swiper_main .swiper-slide picture img { width: auto !important; height: auto !important; max-width: 100% !important; max-height: 100% !important; }' : '
		#' . $uid . ' .fc_swiper_main .swiper-slide > a { display: block; height: 100%; }
		#' . $uid . ' .fc_swiper_main .swiper-slide img,
		#' . $uid . ' .fc_swiper_main .swiper-slide picture img { width: 100% !important; height: 100% !important; max-width: 100% !important; object-fit: cover; }') : '') . ($carousel_padding ? '
		#' . $uid . ' .fc_swiper_main { padding: ' . $carousel_padding . '; box-sizing: border-box; }' : '') . '
		#' . $uid . ' .fc_swiper_thumbs .swiper-slide { width: auto !important; opacity: 0.45; transition: opacity 0.25s ease; }
		#' . $uid . ' .fc_swiper_thumbs .swiper-slide-thumb-active { opacity: 1; }
		#' . $uid . ' .fc_swiper_thumbs .swiper-slide img { display: block; border-radius: 4px; border: 2px solid transparent; }
		#' . $uid . ' .fc_swiper_thumbs .swiper-slide-thumb-active img { border-color: var(--swiper-theme-color, #007aff); }
		' . ($thumb_is_vertical ? '
		#' . $uid . ' { display: flex; align-items: stretch; }
		#' . $uid . '.fc_swiper_thumbs_left { flex-direction: row-reverse; }
		#' . $uid . ' .fc_swiper_main { flex: 1; min-width: 0; }
		#' . $uid . ' .fc_swiper_thumbs_vertical { flex: 0 0 auto; width: ' . $thumb_height . 'px; padding: 0; margin: 0 !important; }
		#' . $uid . ' .fc_swiper_thumbs_vertical .swiper-wrapper { height: 100%; }
		#' . $uid . ' .fc_swiper_thumbs_vertical .swiper-slide { width: 100% !important; height: auto !important; opacity: 0.45; transition: opacity 0.25s ease; }
		#' . $uid . ' .fc_swiper_thumbs_vertical .swiper-slide-thumb-active { opacity: 1; }
		#' . $uid . ' .fc_swiper_thumbs_vertical .swiper-slide img { width: 100% !important; height: auto !important; max-width: none !important; }
		#' . $uid . ' .fc_swiper_thumbs_vertical .swiper-slide-thumb-active img { border-color: var(--swiper-theme-color, #007aff); }' : '') . '
		#' . $uid . ' .swiper-pagination-bullet { width: 10px; height: 10px; }
		#' . $uid . ' .swiper-pagination-fraction { font-size: 14px; color: #fff; background: rgba(0,0,0,.45); padding: 4px 12px; border-radius: 20px; }
		#' . $uid . ' .swiper-pagination-progressbar { background: rgba(0,0,0,.3); border-radius: 20px; overflow: hidden; }
		#' . $uid . ' .swiper-pagination-progressbar .swiper-pagination-progressbar-fill { background: var(--swiper-theme-color, #007aff); }
		#' . $uid . ' .swiper-scrollbar { --swiper-scrollbar-size: 6px; --swiper-scrollbar-bg-color: rgba(0,0,0,.3); --swiper-scrollbar-drag-bg-color: var(--swiper-theme-color, #007aff); }
		#' . $uid . ' .swiper-scrollbar-drag { border-radius: 6px; }
		#' . $uid . ' .swiper-button-prev,
		#' . $uid . ' .swiper-button-next { color: ' . ($nav_color ?: '#fff') . '; text-shadow: 0 1px 3px rgba(0,0,0,.5); }
		' . ($direction === 'vertical' ? '
		#' . $uid . ' { min-width: 0; }
		#' . $uid . ' .fc_swiper_main { width: 100%; max-width: 100%; }
		#' . $uid . ' .fc_swiper_main.swiper-vertical .swiper-button-prev,
		#' . $uid . ' .fc_swiper_main.swiper-vertical .swiper-button-next { left: 50%; right: auto; margin-top: 0; }
		#' . $uid . ' .fc_swiper_main.swiper-vertical .swiper-button-prev { top: 10px; transform: translateX(-50%) rotate(90deg); }
		#' . $uid . ' .fc_swiper_main.swiper-vertical .swiper-button-next { top: auto; bottom: 10px; transform: translateX(-50%) rotate(90deg); }' : '') . '
	</style>

	<div id="' . $uid . '" class="fc_swiper_container fc_swiper_thumbs_' . $thumb_position . '"
		data-speed="' . $speed . '"
		data-loop="' . ($loop ? 1 : 0) . '"
		data-rewind="' . ($rewind ? 1 : 0) . '"
		data-grid-rows="' . $grid_rows . '"
		data-grid-fill="' . $grid_fill . '"
		data-autoplay="' . ($autoplay ? 1 : 0) . '"
		data-autoplay-delay="' . $autoplay_delay . '"
		data-pagination="' . ($show_pagination ? 1 : 0) . '"
		data-pag-type="' . $pag_type . '"
		data-pag-clickable="' . ($pag_clickable ? 1 : 0) . '"
		data-pag-dynamic="' . ($pag_dynamic ? 1 : 0) . '"
		data-pag-hideonclick="' . ($pag_hideonclick ? 1 : 0) . '"
		data-pag-fraction="' . $pag_fraction . '"
		data-nav="' . ($show_nav ? 1 : 0) . '"
		data-thumbs="' . ($show_thumbs && count($swiper_thumbs) ? 1 : 0) . '"
		data-thumb-vertical="' . ($thumb_is_vertical ? 1 : 0) . '"
		data-direction="' . $direction . '"
		data-auto-height="' . ($auto_height ? 1 : 0) . '"
		data-effect="' . $effect . '"
		data-slide-shadows="' . $slide_shadows . '"
		data-cube-shadow="' . $cube_shadow . '"
		data-flip-limit-rotation="' . $flip_limit_rotation . '"
		data-cards-rotate="' . $cards_rotate . '"
		data-cards-per-slide-offset="' . $cards_per_slide_offset . '"
		data-cards-per-slide-rotate="' . $cards_per_slide_rotate . '"
		data-coverflow-rotate="' . $coverflow_rotate . '"
		data-coverflow-stretch="' . $coverflow_stretch . '"
		data-coverflow-depth="' . $coverflow_depth . '"
		data-coverflow-scale="' . $coverflow_scale . '"
		data-space="' . $space_between . '"
		data-slides-per-view="' . $slides_per_view . '"
		data-slides-per-group="' . $slides_per_group . '"
		data-spv-tablet="' . $spv_tablet . '"
		data-spv-phone="' . $spv_phone . '"
		data-centered="' . ($centered ? 1 : 0) . '"
		data-grab-cursor="' . ($grab_cursor ? 1 : 0) . '"
		data-keyboard="' . ($keyboard ? 1 : 0) . '"
		data-mousewheel="' . ($mousewheel ? 1 : 0) . '"
		data-scrollbar="' . ($show_scrollbar ? 1 : 0) . '"
		data-scrollbar-draggable="' . ($scrollbar_draggable ? 1 : 0) . '"
		data-scrollbar-hide="' . ($scrollbar_hide ? 1 : 0) . '"
		data-scrollbar-drag-size="' . $scrollbar_drag_size . '"
		style="width:100%; max-width:100%; overflow:hidden;">

		' . ($thumb_position === 'above' ? $thumbs_html : '') . '

		<div class="swiper fc_swiper_main">
			<div class="swiper-wrapper">
				' . $field->{$prop} . '
			</div>
			' . ($show_pagination ? '<div class="swiper-pagination"></div>' : '') . '
			' . ($show_nav ? '<div class="swiper-button-prev"></div><div class="swiper-button-next"></div>' : '') . '
			' . ($show_scrollbar ? '<div class="swiper-scrollbar"></div>' : '') . '
		</div>' . '

		' . ($thumb_position !== 'above' ? $thumbs_html : '') . '

	</div>
	<div class="fcclear"></div>
	';

	// Apply open/close tags
	$field->{$prop}  = $opentag . $field->{$prop} . $closetag;
}